import { PrismaClient } from "@prisma/client";

export async function seedQuiz(prisma: PrismaClient) {
  console.log("  → Seeding quiz questions...");

  const enLang = await prisma.language.findUnique({ where: { code: "EN" } });
  if (!enLang) throw new Error("Language EN chưa được seed.");

  const questions = [
    // ── MULTIPLE CHOICE A1 ────────────────────────────────────────────────────
    {
      id: "q-en-mc-01",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: 'Choose the correct form: "She ___ a teacher."',
      options: ["am", "is", "are", "be"],
      correctAns: "is",
      explanation: 'Dùng "is" với chủ ngữ He/She/It.',
    },
    {
      id: "q-en-mc-02",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: "Which sentence is correct?",
      options: ["I am not go to school today.", "I do not go to school today.", "I not go to school today.", "I does not go to school today."],
      correctAns: "I do not go to school today.",
      explanation: 'Phủ định thì hiện tại đơn với I/You/We/They dùng "do not".',
    },
    {
      id: "q-en-mc-03",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: 'What is the plural of "child"?',
      options: ["childs", "childes", "children", "child"],
      correctAns: "children",
      explanation: '"Children" là số nhiều bất quy tắc của "child".',
    },
    {
      id: "q-en-mc-04",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: 'Choose the correct article: "___ apple a day keeps the doctor away."',
      options: ["A", "An", "The", "No article"],
      correctAns: "An",
      explanation: 'Dùng "an" trước từ bắt đầu bằng nguyên âm (a, e, i, o, u). "Apple" bắt đầu bằng "a".',
    },
    {
      id: "q-en-mc-05",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: 'What does "happy" mean in Vietnamese?',
      options: ["buồn", "tức giận", "vui vẻ / hạnh phúc", "mệt mỏi"],
      correctAns: "vui vẻ / hạnh phúc",
      explanation: '"Happy" nghĩa là vui vẻ hoặc hạnh phúc.',
    },
    {
      id: "q-en-mc-06",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: 'Choose the correct possessive: "This is ___ book." (belonging to him)',
      options: ["he", "him", "his", "her"],
      correctAns: "his",
      explanation: '"His" là tính từ sở hữu của "he" (anh ấy).',
    },
    {
      id: "q-en-mc-07",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: "Which word is a verb?",
      options: ["beautiful", "study", "happy", "school"],
      correctAns: "study",
      explanation: '"Study" là động từ (học tập). Các từ còn lại là tính từ hoặc danh từ.',
    },
    {
      id: "q-en-mc-08",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: '"What time ___ it?" — Choose the correct word.',
      options: ["am", "is", "are", "do"],
      correctAns: "is",
      explanation: '"What time is it?" — dùng "is" vì chủ ngữ là "it".',
    },

    // ── MULTIPLE CHOICE A2 ────────────────────────────────────────────────────
    {
      id: "q-en-mc-09",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: "She ___ TV when I called her. (watch)",
      options: ["watched", "was watching", "is watching", "watches"],
      correctAns: "was watching",
      explanation: "Dùng Past Continuous (was/were + V-ing) cho hành động đang xảy ra khi có hành động khác xen vào.",
    },
    {
      id: "q-en-mc-10",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: "I ___ to Japan twice. (be)",
      options: ["was", "have been", "went", "had been"],
      correctAns: "have been",
      explanation: "Dùng Present Perfect (have/has + V3) để nói về kinh nghiệm trong cuộc đời.",
    },
    {
      id: "q-en-mc-11",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: "The book is ___ the table.",
      options: ["in", "on", "at", "by"],
      correctAns: "on",
      explanation: 'Dùng "on" cho vật trên bề mặt.',
    },
    {
      id: "q-en-mc-12",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: 'Choose the comparative form: "This exercise is ___ than the last one." (difficult)',
      options: ["more difficult", "difficulter", "most difficult", "the most difficult"],
      correctAns: "more difficult",
      explanation: 'Tính từ dài (≥3 âm tiết) dùng "more + adj" để so sánh hơn.',
    },

    // ── FILL IN THE BLANK A1 ──────────────────────────────────────────────────
    {
      id: "q-en-fill-01",
      type: "FILL_BLANK",
      level: "A1",
      question: 'Complete the sentence: "I ___ (eat) breakfast every morning."',
      options: null,
      correctAns: "eat",
      explanation: "Thì hiện tại đơn với I, dùng động từ nguyên thể: eat.",
    },
    {
      id: "q-en-fill-02",
      type: "FILL_BLANK",
      level: "A1",
      question: 'Fill in the blank: "She ___ (not/like) coffee."',
      options: null,
      correctAns: "doesn't like",
      explanation: "Phủ định hiện tại đơn với She: doesn't + V nguyên thể.",
    },
    {
      id: "q-en-fill-03",
      type: "FILL_BLANK",
      level: "A1",
      question: 'Complete: "There ___ two cats in the garden."',
      options: null,
      correctAns: "are",
      explanation: 'Dùng "are" với danh từ số nhiều (two cats).',
    },
    {
      id: "q-en-fill-04",
      type: "FILL_BLANK",
      level: "A2",
      question: 'Fill in: "He ___ (go) to school yesterday."',
      options: null,
      correctAns: "went",
      explanation: '"Went" là quá khứ bất quy tắc của "go".',
    },
    {
      id: "q-en-fill-05",
      type: "FILL_BLANK",
      level: "A2",
      question: 'Complete: "I have lived in Hanoi ___ 5 years."',
      options: null,
      correctAns: "for",
      explanation: 'Dùng "for" với khoảng thời gian (5 years). Dùng "since" với mốc thời gian (2019).',
    },

    // ── ARRANGE A1 ────────────────────────────────────────────────────────────
    {
      id: "q-en-arr-01",
      type: "ARRANGE",
      level: "A1",
      question: "Arrange the words to make a correct sentence: [every / I / day / English / study]",
      options: ["every", "I", "day", "English", "study"],
      correctAns: "I study English every day",
      explanation: "Cấu trúc câu: Chủ ngữ + Động từ + Tân ngữ + Trạng ngữ thời gian.",
    },
    {
      id: "q-en-arr-02",
      type: "ARRANGE",
      level: "A1",
      question: "Arrange: [is / name / your / What]",
      options: ["is", "name", "your", "What"],
      correctAns: "What is your name",
      explanation: 'Câu hỏi với "what": What + is + chủ ngữ?',
    },
    {
      id: "q-en-arr-03",
      type: "ARRANGE",
      level: "A2",
      question: "Arrange: [does / Where / work / she]",
      options: ["does", "Where", "work", "she"],
      correctAns: "Where does she work",
      explanation: "Câu hỏi Wh- với hiện tại đơn: Wh- + does + chủ ngữ + V?",
    },

    // ── MULTIPLE CHOICE B1 ────────────────────────────────────────────────────
    {
      id: "q-en-mc-b1-01",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: "If I ___ rich, I would travel the world.",
      options: ["am", "was", "were", "will be"],
      correctAns: "were",
      explanation: 'Câu điều kiện loại 2: If + Simple Past (dùng "were" cho tất cả chủ ngữ), would + V.',
    },
    {
      id: "q-en-mc-b1-02",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: "She asked me ___ I was happy.",
      options: ["that", "if", "what", "which"],
      correctAns: "if",
      explanation: 'Câu hỏi gián tiếp Yes/No dùng "if" hoặc "whether".',
    },
    {
      id: "q-en-mc-b1-03",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: "The report ___ by the team last week.",
      options: ["was written", "written", "is written", "has written"],
      correctAns: "was written",
      explanation: "Câu bị động thì quá khứ đơn: was/were + V3.",
    },
    // ── MULTIPLE CHOICE B2 ────────────────────────────────────────────────────
    {
      id: "q-en-mc-b2-01",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: "The man ___ car was stolen called the police.",
      options: ["who", "whom", "whose", "which"],
      correctAns: "whose",
      explanation: "whose dùng để chỉ sở hữu trong mệnh đề quan hệ.",
    },
    {
      id: "q-en-mc-b2-02",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: "I wish I ___ harder for the exam last week.",
      options: ["study", "studied", "had studied", "would study"],
      correctAns: "had studied",
      explanation: "Wish + Past Perfect diễn tả sự hối tiếc về quá khứ.",
    },
    {
      id: "q-en-mc-b2-03",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: "This bridge ___ in 1998.",
      options: ["built", "was built", "is built", "has built"],
      correctAns: "was built",
      explanation: "Bị động thì quá khứ đơn cho sự kiện lịch sử đã hoàn thành.",
    },
    {
      id: "q-en-fill-b2-01",
      type: "FILL_BLANK",
      level: "B2",
      question: "She said she ___ (finish) the project by Friday.",
      options: null,
      correctAns: "would have finished",
      explanation: "Tường thuật câu tương lai hoàn thành: will have + V3 → would have + V3.",
    },
    {
      id: "q-en-mc-b2-04",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: "The book ___ I bought yesterday is fascinating.",
      options: ["who", "whose", "that", "where"],
      correctAns: "that",
      explanation: "that (hoặc which) thay thế cho vật làm tân ngữ trong mệnh đề quan hệ xác định.",
    },
    {
      id: "q-en-mc-b2-05",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: "If only I ___ about the meeting earlier!",
      options: ["know", "knew", "had known", "would know"],
      correctAns: "had known",
      explanation: "If only + Past Perfect diễn tả sự hối tiếc về quá khứ, tương tự wish.",
    },
    {
      id: "q-en-mc-c1-01",
      type: "MULTIPLE_CHOICE",
      level: "C1",
      question: "___ have I seen such a beautiful sunset.",
      options: ["Never", "I never", "Never I", "Not never"],
      correctAns: "Never",
      explanation: 'Đảo ngữ với "Never" đứng đầu câu: Never + trợ động từ + S + V.',
    },
    {
      id: "q-en-mc-c1-02",
      type: "MULTIPLE_CHOICE",
      level: "C1",
      question: "If I had studied medicine, I ___ a doctor now.",
      options: ["would be", "would have been", "will be", "was"],
      correctAns: "would be",
      explanation: "Mixed conditional: điều kiện quá khứ (had studied) → kết quả hiện tại (would be).",
    },
    {
      id: "q-en-fill-c1-01",
      type: "FILL_BLANK",
      level: "C1",
      question: "Not only ___ she pass the exam, but she also got the highest score.",
      options: null,
      correctAns: "did",
      explanation: 'Đảo ngữ với "Not only" đứng đầu câu cần trợ động từ did trước chủ ngữ.',
    },
    {
      id: "q-en-mc-c1-03",
      type: "MULTIPLE_CHOICE",
      level: "C1",
      question: "If I weren't afraid of heights, I ___ skydiving last month.",
      options: ["would go", "would have gone", "will go", "went"],
      correctAns: "would have gone",
      explanation: "Mixed conditional: tính chất hiện tại (weren't afraid) → kết quả quá khứ (would have gone).",
    },
    {
      id: "q-en-mc-c2-01",
      type: "MULTIPLE_CHOICE",
      level: "C2",
      question: "___ was John who broke the window.",
      options: ["This", "It", "That", "He"],
      correctAns: "It",
      explanation: 'It-cleft: "It + be + thành phần nhấn mạnh + that/who" để nhấn mạnh chủ thể.',
    },
    {
      id: "q-en-mc-c2-02",
      type: "MULTIPLE_CHOICE",
      level: "C2",
      question: "___ I need is a good night's sleep.",
      options: ["It", "What", "That", "This"],
      correctAns: "What",
      explanation: "What-cleft dùng để nhấn mạnh 1 ý tưởng/nhu cầu trừu tượng.",
    },
    {
      id: "q-en-fill-c2-01",
      type: "FILL_BLANK",
      level: "C2",
      question: '___ I known about the traffic, I would have left earlier. (đảo ngữ trang trọng của "If I had known")',
      options: null,
      correctAns: "Had",
      explanation: 'Đảo ngữ điều kiện loại 3 trang trọng: Had + S + V3, bỏ "If".',
    },
    {
      id: "q-en-mc-c2-03",
      type: "MULTIPLE_CHOICE",
      level: "C2",
      question: 'Chọn câu đảo ngữ đúng nghĩa "If I were in your position, I would accept the offer":',
      options: ["I were in your position...", "Were I in your position...", "If were I...", "Was I in your position..."],
      correctAns: "Were I in your position...",
      explanation: 'Đảo ngữ điều kiện loại 2 trang trọng: Were + S..., bỏ "If".',
    },
  ];

  for (const q of questions) {
    await prisma.quizQuestion.upsert({
      where: { id: q.id },
      update: {},
      create: {
        id: q.id,
        languageId: enLang.id,
        type: q.type as any,
        level: q.level as any,
        question: q.question,
        options: q.options ? q.options : undefined,
        correctAns: q.correctAns,
        explanation: q.explanation,
      },
    });
  }

  console.log(`  ✓ Quiz EN seeded: ${questions.length} câu hỏi (A1→C2)`);

  // ── Tiếng Trung ──────────────────────────────────────────────────────────
  const zhLang = await prisma.language.findUnique({ where: { code: "ZH" } });
  if (!zhLang) throw new Error("Language ZH chưa được seed.");

  const zhQuestions = [
    {
      id: "q-zh-mc-01",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: "选择正确的答案: 我___学生。(Chọn đáp án đúng)",
      options: ["是", "不", "的", "吗"],
      correctAns: "是",
      explanation: '是 (shì) nghĩa là "là", dùng nối chủ ngữ với danh từ.',
    },
    {
      id: "q-zh-mc-02",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: '"你好" nghĩa là gì?',
      options: ["Tạm biệt", "Xin chào", "Cảm ơn", "Xin lỗi"],
      correctAns: "Xin chào",
      explanation: "你好 (nǐ hǎo) là lời chào phổ biến nhất trong tiếng Trung.",
    },
    {
      id: "q-zh-mc-03",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: "Chọn lượng từ đúng: 一___书 (một quyển sách)",
      options: ["个", "本", "张", "杯"],
      correctAns: "本",
      explanation: "本 (běn) là lượng từ dùng cho sách, vở.",
    },
    {
      id: "q-zh-mc-04",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: '"谢谢" nghĩa là gì?',
      options: ["Xin chào", "Cảm ơn", "Không sao", "Làm ơn"],
      correctAns: "Cảm ơn",
      explanation: "谢谢 (xièxie) nghĩa là cảm ơn.",
    },
    {
      id: "q-zh-mc-05",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: 'Chọn câu đúng khi diễn đạt "Tôi đã ăn cơm rồi":',
      options: ["我吃饭。", "我吃饭了。", "我了吃饭。", "我不吃饭了。"],
      correctAns: "我吃饭了。",
      explanation: "了 đặt sau động từ (hoặc cuối câu) để chỉ hành động đã hoàn thành.",
    },
    {
      id: "q-zh-mc-06",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: '"这是我___书。" (Đây là sách của tôi.) Điền từ còn thiếu:',
      options: ["是", "的", "了", "吗"],
      correctAns: "的",
      explanation: "的 (de) là trợ từ sở hữu, đặt sau người sở hữu.",
    },
    {
      id: "q-zh-mc-07",
      type: "FILL_BLANK",
      level: "A1",
      question: "我___老师。(Tôi không phải là giáo viên.) — điền phần phủ định của 是",
      options: null,
      correctAns: "不是",
      explanation: '不是 (bú shì) là phủ định của 是 — "không phải là".',
    },
    {
      id: "q-zh-mc-08",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: 'Số "2" khi đứng trước lượng từ (vd: 2 người) đọc là gì?',
      options: ["二 (èr)", "两 (liǎng)", "双 (shuāng)", "第二 (dì èr)"],
      correctAns: "两 (liǎng)",
      explanation: "两 dùng khi đếm số lượng trước lượng từ, 二 dùng khi đếm số thứ tự/số học thông thường.",
    },
    {
      id: "q-zh-mc-b1-01",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: "我___他高。(Tôi cao hơn anh ấy.) — chọn từ đúng",
      options: ["是", "比", "的", "了"],
      correctAns: "比",
      explanation: '比 (bǐ) dùng trong cấu trúc so sánh "A比B+tính từ".',
    },
    {
      id: "q-zh-mc-b1-02",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: 'Câu nào đúng khi nói "Tôi không cao bằng anh ấy"?',
      options: ["我不比他高。", "我没有他高。", "我比他不高。", "我不是他高。"],
      correctAns: "我没有他高。",
      explanation: "Phủ định của câu so sánh 比 dùng 没有, không dùng 不比.",
    },
    {
      id: "q-zh-mc-b1-03",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: '"听得懂" nghĩa là gì?',
      options: ["Nghe không hiểu", "Nghe hiểu được", "Không muốn nghe", "Nghe rất to"],
      correctAns: "Nghe hiểu được",
      explanation: "得 + bổ ngữ kết quả diễn tả khả năng đạt được kết quả của hành động.",
    },
    {
      id: "q-zh-fill-b1-01",
      type: "FILL_BLANK",
      level: "B1",
      question: "这个字太小，我看___见。(Chữ này quá nhỏ, tôi không nhìn thấy.)",
      options: null,
      correctAns: "不",
      explanation: "看不见 — bổ ngữ khả năng thể phủ định: Động từ + 不 + bổ ngữ.",
    },
    {
      id: "q-zh-mc-b1-04",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: '"这本书怎么样？" (nghĩa gần đúng nhất)',
      options: ["Quyển sách này bao nhiêu tiền?", "Quyển sách này thế nào?", "Quyển sách này ở đâu?", "Đây là quyển sách gì?"],
      correctAns: "Quyển sách này thế nào?",
      explanation: "怎么样 (zěnmeyàng) dùng để hỏi ý kiến/đánh giá về điều gì đó.",
    },
    {
      id: "q-zh-mc-b1-05",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: 'Chọn câu đúng nghĩa "Tôi cao bằng anh ấy":',
      options: ["我跟他一样高。", "我比他一样高。", "我和他比高。", "我是他一样高。"],
      correctAns: "我跟他一样高。",
      explanation: "Cấu trúc so sánh ngang bằng: A 跟 B 一样 + tính từ.",
    },
    {
      id: "q-zh-mc-b2-01",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: "我___书放在桌子上了。(Tôi đã đặt sách lên bàn.) — chọn từ đúng",
      options: ["把", "被", "比", "的"],
      correctAns: "把",
      explanation: "把 dùng để nhấn mạnh việc xử lý 1 đối tượng cụ thể và kết quả.",
    },
    {
      id: "q-zh-mc-b2-02",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: '"我的钱包被偷了" nghĩa là gì?',
      options: ["Tôi đánh rơi ví", "Ví của tôi bị lấy trộm", "Tôi mua một cái ví", "Ví của tôi rất đẹp"],
      correctAns: "Ví của tôi bị lấy trộm",
      explanation: "被 (bèi) tạo câu bị động, thường mang sắc thái không may mắn/tiêu cực.",
    },
    {
      id: "q-zh-fill-b2-01",
      type: "FILL_BLANK",
      level: "B2",
      question: "请___门关上。(Xin hãy đóng cửa lại.)",
      options: null,
      correctAns: "把",
      explanation: "Câu 把 dùng khi yêu cầu xử lý 1 đối tượng cụ thể (cánh cửa) với kết quả rõ ràng (đóng lại).",
    },
    {
      id: "q-zh-mc-b2-03",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: "Câu nào đúng ngữ pháp?",
      options: ["我把书看。", "我把书看完了。", "书把我看完了。", "我把看书完了。"],
      correctAns: "我把书看完了。",
      explanation: "Động từ trong câu 把 bắt buộc phải có bổ ngữ kết quả đi kèm (完了), không thể đứng trơ trọi.",
    },
    {
      id: "q-zh-mc-c1-01",
      type: "MULTIPLE_CHOICE",
      level: "C1",
      question: "她___聪明，___很努力。(Cô ấy không những thông minh mà còn rất chăm chỉ.)",
      options: ["虽然...但是", "不但...而且", "既然...就", "除非...否则"],
      correctAns: "不但...而且",
      explanation: '不但...而且 nghĩa là "không những...mà còn", diễn tả tăng tiến.',
    },
    {
      id: "q-zh-mc-c1-02",
      type: "MULTIPLE_CHOICE",
      level: "C1",
      question: '"他走进来了" nghĩa là gì?',
      options: ["Anh ấy chạy ra ngoài", "Anh ấy đi vào (phía người nói)", "Anh ấy đứng lại", "Anh ấy đi ra (xa người nói)"],
      correctAns: "Anh ấy đi vào (phía người nói)",
      explanation: "进来 là bổ ngữ xu hướng phức hợp: 进 (vào) + 来 (về phía người nói).",
    },
    {
      id: "q-zh-fill-c1-01",
      type: "FILL_BLANK",
      level: "C1",
      question: "___你已经决定了，我们就支持你。(Đã như vậy bạn quyết định rồi thì chúng tôi ủng hộ bạn.)",
      options: null,
      correctAns: "既然",
      explanation: '既然...就 nghĩa là "đã như vậy...thì", diễn tả suy luận từ 1 sự thật đã biết.',
    },
    {
      id: "q-zh-mc-c1-03",
      type: "MULTIPLE_CHOICE",
      level: "C1",
      question: '"想起来" nghĩa bóng là gì?',
      options: ["Đứng dậy", "Nhớ ra, chợt nghĩ ra", "Đi lên trên", "Nói to lên"],
      correctAns: "Nhớ ra, chợt nghĩ ra",
      explanation: '想起来 là nghĩa bóng của bổ ngữ xu hướng 起来, không phải nghĩa đen "nghĩ lên".',
    },
  ];

  for (const q of zhQuestions) {
    await prisma.quizQuestion.upsert({
      where: { id: q.id },
      update: {},
      create: {
        id: q.id,
        languageId: zhLang.id,
        type: q.type as any,
        level: q.level as any,
        question: q.question,
        options: q.options ? q.options : undefined,
        correctAns: q.correctAns,
        explanation: q.explanation,
      },
    });
  }
  console.log(`  ✓ Quiz ZH seeded: ${zhQuestions.length} câu hỏi (A1→C1)`);

  // ── Tiếng Nhật ───────────────────────────────────────────────────────────
  const jaLang = await prisma.language.findUnique({ where: { code: "JA" } });
  if (!jaLang) throw new Error("Language JA chưa được seed.");

  const jaQuestions = [
    {
      id: "q-ja-mc-01",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: '"こんにちは" nghĩa là gì?',
      options: ["Tạm biệt", "Xin chào (ban ngày)", "Cảm ơn", "Xin lỗi"],
      correctAns: "Xin chào (ban ngày)",
      explanation: "こんにちは (konnichiwa) là lời chào dùng vào ban ngày.",
    },
    {
      id: "q-ja-mc-02",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: "Chọn trợ từ đúng: 私___学生です。(Tôi là học sinh.)",
      options: ["を", "は", "に", "で"],
      correctAns: "は",
      explanation: "は (wa) đánh dấu chủ đề của câu.",
    },
    {
      id: "q-ja-mc-03",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: '"ありがとう" nghĩa là gì?',
      options: ["Xin chào", "Cảm ơn", "Xin lỗi", "Không sao"],
      correctAns: "Cảm ơn",
      explanation: "ありがとう (arigatou) nghĩa là cảm ơn.",
    },
    {
      id: "q-ja-mc-04",
      type: "MULTIPLE_CHOICE",
      level: "A1",
      question: "Chọn trợ từ đúng: 水___飲みます。(Uống nước.)",
      options: ["は", "が", "を", "に"],
      correctAns: "を",
      explanation: 'を đánh dấu tân ngữ trực tiếp của động từ, đọc là "o".',
    },
    {
      id: "q-ja-mc-05",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: "Thể quá khứ lịch sự của 食べます (ăn) là gì?",
      options: ["食べません", "食べました", "食べませんでした", "食べます"],
      correctAns: "食べました",
      explanation: "～ました là thể quá khứ khẳng định lịch sự (masu-form).",
    },
    {
      id: "q-ja-mc-06",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: "Chọn trợ từ đúng: 図書館___勉強します。(Học ở thư viện.)",
      options: ["に", "で", "を", "は"],
      correctAns: "で",
      explanation: "で chỉ nơi hành động diễn ra.",
    },
    {
      id: "q-ja-mc-07",
      type: "FILL_BLANK",
      level: "A1",
      question: "これ___本です。(Đây là quyển sách.) — điền trợ từ còn thiếu",
      options: null,
      correctAns: "は",
      explanation: 'は đánh dấu chủ đề "これ" (đây).',
    },
    {
      id: "q-ja-mc-08",
      type: "MULTIPLE_CHOICE",
      level: "A2",
      question: 'Trợ từ nào dùng để chỉ thời điểm cụ thể, vd "7時___起きます" (dậy lúc 7 giờ)?',
      options: ["で", "を", "に", "は"],
      correctAns: "に",
      explanation: "に dùng cho thời điểm cụ thể và điểm đến.",
    },
    {
      id: "q-ja-mc-b1-01",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: "Chọn thể て đúng của 飲む (uống):",
      options: ["飲て", "飲んで", "飲いて", "飲した"],
      correctAns: "飲んで",
      explanation: "Động từ đuôi む chuyển thể て thành んで: 飲む→飲んで.",
    },
    {
      id: "q-ja-mc-b1-02",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: '"ここに座ってください" nghĩa là gì?',
      options: ["Tôi ngồi ở đây", "Xin hãy ngồi đây", "Bạn có thể ngồi đây không?", "Đừng ngồi đây"],
      correctAns: "Xin hãy ngồi đây",
      explanation: "～てください là mẫu câu yêu cầu lịch sự, dùng thể て + ください.",
    },
    {
      id: "q-ja-mc-b1-03",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: "日本語は英語___難しいです。(Tiếng Nhật khó hơn tiếng Anh.)",
      options: ["が", "より", "ほう", "でも"],
      correctAns: "より",
      explanation: 'より dùng trong cấu trúc so sánh "A は B より + tính từ".',
    },
    {
      id: "q-ja-fill-b1-01",
      type: "FILL_BLANK",
      level: "B1",
      question: "今、食べ___います。(Bây giờ tôi đang ăn.) — điền phần còn thiếu của thể tiếp diễn",
      options: null,
      correctAns: "て",
      explanation: "Thể tiếp diễn: Động từ thể て + います.",
    },
    {
      id: "q-ja-mc-b1-04",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: "入って___いいですか？(Tôi vào được không?) — điền trợ từ",
      options: ["が", "も", "は", "を"],
      correctAns: "も",
      explanation: "～てもいいですか là mẫu câu xin phép.",
    },
    {
      id: "q-ja-mc-b1-05",
      type: "MULTIPLE_CHOICE",
      level: "B1",
      question: 'Chọn câu đúng nghĩa "Anh tôi cao ngang bố tôi":',
      options: ["兄は父より背が高いです。", "兄は父と同じぐらい背が高いです。", "兄は父ほど高くないです。", "兄は父が高いです。"],
      correctAns: "兄は父と同じぐらい背が高いです。",
      explanation: "So sánh ngang bằng: A は B と 同じぐらい + tính từ.",
    },
    {
      id: "q-ja-mc-b2-01",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: "私は先生に___。(Tôi được thầy khen.) — chọn thể bị động đúng của 褒める",
      options: ["褒めます", "褒められました", "褒めさせました", "褒めています"],
      correctAns: "褒められました",
      explanation: "Thể bị động của động từ nhóm II: bỏ る thêm られる.",
    },
    {
      id: "q-ja-mc-b2-02",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: '"雨に降られました" diễn tả ý nghĩa gì?',
      options: ["Tôi thích mưa", "Tôi bị mắc mưa (phiền toái)", "Trời sắp mưa", "Tôi làm mưa rơi"],
      correctAns: "Tôi bị mắc mưa (phiền toái)",
      explanation: 'Đây là "bị động gây phiền" (迷惑受身) — đặc trưng riêng của tiếng Nhật.',
    },
    {
      id: "q-ja-fill-b2-01",
      type: "FILL_BLANK",
      level: "B2",
      question: "母は子供に野菜を食べ___ました。(Mẹ bắt con ăn rau.) — điền thể sai khiến",
      options: null,
      correctAns: "させ",
      explanation: "Thể sai khiến của động từ nhóm II: bỏ る thêm させる.",
    },
    {
      id: "q-ja-mc-b2-03",
      type: "MULTIPLE_CHOICE",
      level: "B2",
      question: '"私は毎日残業させられます" nghĩa là gì?',
      options: ["Tôi thích làm thêm giờ", "Tôi bị bắt làm thêm giờ mỗi ngày", "Tôi cho phép làm thêm giờ", "Tôi không làm thêm giờ"],
      correctAns: "Tôi bị bắt làm thêm giờ mỗi ngày",
      explanation: "Thể sai khiến bị động (使役受身) diễn tả bị buộc làm điều không muốn.",
    },
    {
      id: "q-ja-mc-c1-01",
      type: "MULTIPLE_CHOICE",
      level: "C1",
      question: "Chọn Tôn kính ngữ đúng của 行く (đi) khi nói về cấp trên:",
      options: ["参る", "いたす", "いらっしゃる", "申す"],
      correctAns: "いらっしゃる",
      explanation: "いらっしゃる là Tôn kính ngữ, dùng để nâng cao hành động của người khác (cấp trên/khách).",
    },
    {
      id: "q-ja-mc-c1-02",
      type: "MULTIPLE_CHOICE",
      level: "C1",
      question: "Chọn Khiêm nhường ngữ đúng của 行く khi nói về bản thân với cấp trên:",
      options: ["いらっしゃる", "参る", "おっしゃる", "召し上がる"],
      correctAns: "参る",
      explanation: "参る là Khiêm nhường ngữ, dùng để hạ thấp hành động của bản thân.",
    },
    {
      id: "q-ja-mc-c1-03",
      type: "MULTIPLE_CHOICE",
      level: "C1",
      question: "Câu nào diễn tả thông tin nghe được từ dự báo thời tiết (truyền văn)?",
      options: ["雨が降るらしい", "雨が降るそうだ", "雨が降るようだ", "雨が降るみたい"],
      correctAns: "雨が降るそうだ",
      explanation: "そうだ dùng khi thuật lại thông tin nghe/đọc được từ nguồn khác (vd dự báo thời tiết).",
    },
    {
      id: "q-ja-fill-c1-01",
      type: "FILL_BLANK",
      level: "C1",
      question: "部屋の電気が消えている。誰もいない___だ。(Đèn phòng tắt rồi. Có vẻ như không có ai ở đó.) — điền từ suy đoán dựa trên quan sát trực tiếp",
      options: null,
      correctAns: "よう",
      explanation: "ようだ dùng khi suy đoán dựa trên quan sát/cảm nhận trực tiếp của người nói.",
    },
  ];

  for (const q of jaQuestions) {
    await prisma.quizQuestion.upsert({
      where: { id: q.id },
      update: {},
      create: {
        id: q.id,
        languageId: jaLang.id,
        type: q.type as any,
        level: q.level as any,
        question: q.question,
        options: q.options ? q.options : undefined,
        correctAns: q.correctAns,
        explanation: q.explanation,
      },
    });
  }
  console.log(`  ✓ Quiz JA seeded: ${jaQuestions.length} câu hỏi (A1→C1)`);
}
