// database/seeds/vocabulary.seed.ts — Seed vocabulary cards
import { PrismaClient } from "@prisma/client";

export async function seedVocabulary(prisma: PrismaClient) {
  console.log("  → Seeding vocabulary...");

  const enLang = await prisma.language.findUnique({ where: { code: "EN" } });
  const zhLang = await prisma.language.findUnique({ where: { code: "ZH" } });
  const jaLang = await prisma.language.findUnique({ where: { code: "JA" } });

  if (!enLang || !zhLang || !jaLang) {
    throw new Error("Languages chưa được seed. Chạy seedLanguages() trước.");
  }

  // ─── Tiếng Anh A1 ────────────────────────────────────────────────────────────
  const englishWords = [
    // Food & Drink
    { word: "apple", pronunciation: "/ˈæp.əl/", meaningVi: "quả táo", exampleSentence: "I eat an apple every day.", topicTags: ["food"], level: "A1" },
    { word: "banana", pronunciation: "/bəˈnɑː.nə/", meaningVi: "quả chuối", exampleSentence: "She likes banana smoothies.", topicTags: ["food"], level: "A1" },
    { word: "water", pronunciation: "/ˈwɔː.tər/", meaningVi: "nước", exampleSentence: "Please give me a glass of water.", topicTags: ["food", "daily"], level: "A1" },
    { word: "rice", pronunciation: "/raɪs/", meaningVi: "cơm, gạo", exampleSentence: "We have rice for lunch.", topicTags: ["food"], level: "A1" },
    { word: "bread", pronunciation: "/bred/", meaningVi: "bánh mì", exampleSentence: "I eat bread for breakfast.", topicTags: ["food"], level: "A1" },
    { word: "milk", pronunciation: "/mɪlk/", meaningVi: "sữa", exampleSentence: "Children should drink milk every day.", topicTags: ["food"], level: "A1" },
    { word: "coffee", pronunciation: "/ˈkɒf.i/", meaningVi: "cà phê", exampleSentence: "He drinks coffee in the morning.", topicTags: ["food", "daily"], level: "A1" },
    { word: "egg", pronunciation: "/eɡ/", meaningVi: "quả trứng", exampleSentence: "I had two eggs for breakfast.", topicTags: ["food"], level: "A1" },

    // Daily Life
    { word: "house", pronunciation: "/haʊs/", meaningVi: "ngôi nhà", exampleSentence: "My house has three bedrooms.", topicTags: ["daily", "home"], level: "A1" },
    { word: "school", pronunciation: "/skuːl/", meaningVi: "trường học", exampleSentence: "She goes to school every day.", topicTags: ["daily", "education"], level: "A1" },
    { word: "book", pronunciation: "/bʊk/", meaningVi: "quyển sách", exampleSentence: "I am reading a good book.", topicTags: ["daily", "education"], level: "A1" },
    { word: "phone", pronunciation: "/fəʊn/", meaningVi: "điện thoại", exampleSentence: "My phone is new.", topicTags: ["daily", "technology"], level: "A1" },
    { word: "car", pronunciation: "/kɑːr/", meaningVi: "xe ô tô", exampleSentence: "He drives a red car.", topicTags: ["daily", "transport"], level: "A1" },
    { word: "money", pronunciation: "/ˈmʌn.i/", meaningVi: "tiền", exampleSentence: "I need more money.", topicTags: ["daily"], level: "A1" },
    { word: "time", pronunciation: "/taɪm/", meaningVi: "thời gian", exampleSentence: "What time is it?", topicTags: ["daily"], level: "A1" },
    { word: "day", pronunciation: "/deɪ/", meaningVi: "ngày", exampleSentence: "Today is a beautiful day.", topicTags: ["daily"], level: "A1" },

    // Family
    { word: "family", pronunciation: "/ˈfæm.ɪ.li/", meaningVi: "gia đình", exampleSentence: "I love my family.", topicTags: ["family"], level: "A1" },
    { word: "mother", pronunciation: "/ˈmʌð.ər/", meaningVi: "mẹ", exampleSentence: "My mother is a teacher.", topicTags: ["family"], level: "A1" },
    { word: "father", pronunciation: "/ˈfɑː.ðər/", meaningVi: "bố", exampleSentence: "My father works in an office.", topicTags: ["family"], level: "A1" },
    { word: "brother", pronunciation: "/ˈbrʌð.ər/", meaningVi: "anh/em trai", exampleSentence: "I have one brother.", topicTags: ["family"], level: "A1" },
    { word: "sister", pronunciation: "/ˈsɪs.tər/", meaningVi: "chị/em gái", exampleSentence: "My sister is very kind.", topicTags: ["family"], level: "A1" },
    { word: "friend", pronunciation: "/frend/", meaningVi: "bạn bè", exampleSentence: "She is my best friend.", topicTags: ["family", "daily"], level: "A1" },

    // Colors
    { word: "red", pronunciation: "/red/", meaningVi: "màu đỏ", exampleSentence: "I like red roses.", topicTags: ["colors"], level: "A1" },
    { word: "blue", pronunciation: "/bluː/", meaningVi: "màu xanh dương", exampleSentence: "The sky is blue.", topicTags: ["colors"], level: "A1" },
    { word: "green", pronunciation: "/ɡriːn/", meaningVi: "màu xanh lá", exampleSentence: "Leaves are green.", topicTags: ["colors"], level: "A1" },
    { word: "white", pronunciation: "/waɪt/", meaningVi: "màu trắng", exampleSentence: "Snow is white.", topicTags: ["colors"], level: "A1" },
    { word: "black", pronunciation: "/blæk/", meaningVi: "màu đen", exampleSentence: "I have a black cat.", topicTags: ["colors"], level: "A1" },

    // Numbers & Time
    { word: "morning", pronunciation: "/ˈmɔː.nɪŋ/", meaningVi: "buổi sáng", exampleSentence: "Good morning!", topicTags: ["daily", "time"], level: "A1" },
    { word: "afternoon", pronunciation: "/ˌɑːf.təˈnuːn/", meaningVi: "buổi chiều", exampleSentence: "I take a nap in the afternoon.", topicTags: ["daily", "time"], level: "A1" },
    { word: "night", pronunciation: "/naɪt/", meaningVi: "buổi tối/đêm", exampleSentence: "Good night, sleep well.", topicTags: ["daily", "time"], level: "A1" },
    { word: "week", pronunciation: "/wiːk/", meaningVi: "tuần", exampleSentence: "There are seven days in a week.", topicTags: ["daily", "time"], level: "A1" },
    { word: "month", pronunciation: "/mʌnθ/", meaningVi: "tháng", exampleSentence: "January is the first month.", topicTags: ["daily", "time"], level: "A1" },
    { word: "year", pronunciation: "/jɪər/", meaningVi: "năm", exampleSentence: "Happy New Year!", topicTags: ["daily", "time"], level: "A1" },

    // Common Verbs A1
    { word: "eat", pronunciation: "/iːt/", meaningVi: "ăn", exampleSentence: "I eat breakfast at 7am.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "drink", pronunciation: "/drɪŋk/", meaningVi: "uống", exampleSentence: "He drinks water every hour.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "sleep", pronunciation: "/sliːp/", meaningVi: "ngủ", exampleSentence: "I sleep 8 hours a day.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "work", pronunciation: "/wɜːrk/", meaningVi: "làm việc", exampleSentence: "She works at a hospital.", topicTags: ["daily", "verbs", "work"], level: "A1" },
    { word: "study", pronunciation: "/ˈstʌd.i/", meaningVi: "học tập", exampleSentence: "I study English every day.", topicTags: ["education", "verbs"], level: "A1" },
    { word: "go", pronunciation: "/ɡəʊ/", meaningVi: "đi", exampleSentence: "Let us go to the park.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "come", pronunciation: "/kʌm/", meaningVi: "đến, đi đến", exampleSentence: "Please come here.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "see", pronunciation: "/siː/", meaningVi: "nhìn thấy, gặp", exampleSentence: "I see you tomorrow.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "like", pronunciation: "/laɪk/", meaningVi: "thích", exampleSentence: "I like this song.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "want", pronunciation: "/wɒnt/", meaningVi: "muốn", exampleSentence: "I want to learn English.", topicTags: ["daily", "verbs"], level: "A1" },

    // Places
    { word: "hospital", pronunciation: "/ˈhɒs.pɪ.təl/", meaningVi: "bệnh viện", exampleSentence: "My mother works in a hospital.", topicTags: ["places"], level: "A1" },
    { word: "supermarket", pronunciation: "/ˈsuː.pəˌmɑː.kɪt/", meaningVi: "siêu thị", exampleSentence: "I buy food at the supermarket.", topicTags: ["places", "daily"], level: "A1" },
    { word: "restaurant", pronunciation: "/ˈres.tər.ɒnt/", meaningVi: "nhà hàng", exampleSentence: "We had dinner at a restaurant.", topicTags: ["places", "food"], level: "A1" },
    { word: "park", pronunciation: "/pɑːrk/", meaningVi: "công viên", exampleSentence: "Children play in the park.", topicTags: ["places", "daily"], level: "A1" },
    { word: "airport", pronunciation: "/ˈeər.pɔːrt/", meaningVi: "sân bay", exampleSentence: "We arrived at the airport early.", topicTags: ["places", "travel"], level: "A2" },

    // Adjectives A1
    { word: "happy", pronunciation: "/ˈhæp.i/", meaningVi: "vui vẻ, hạnh phúc", exampleSentence: "I am very happy today.", topicTags: ["emotions", "adjectives"], level: "A1" },
    { word: "sad", pronunciation: "/sæd/", meaningVi: "buồn", exampleSentence: "She looks sad today.", topicTags: ["emotions", "adjectives"], level: "A1" },
    { word: "big", pronunciation: "/bɪɡ/", meaningVi: "to lớn", exampleSentence: "That is a big house.", topicTags: ["adjectives"], level: "A1" },
    { word: "small", pronunciation: "/smɔːl/", meaningVi: "nhỏ bé", exampleSentence: "She has a small cat.", topicTags: ["adjectives"], level: "A1" },
    { word: "good", pronunciation: "/ɡʊd/", meaningVi: "tốt, ngon", exampleSentence: "This food is very good.", topicTags: ["adjectives", "daily"], level: "A1" },
    { word: "beautiful", pronunciation: "/ˈbjuː.tɪ.fəl/", meaningVi: "đẹp", exampleSentence: "Vietnam is a beautiful country.", topicTags: ["adjectives"], level: "A1" },
    { word: "achieve", pronunciation: "/əˈtʃiːv/", meaningVi: "đạt được", exampleSentence: "She achieved her goal after years of hard work.", topicTags: ["business", "verbs"], level: "B1" },
    { word: "opportunity", pronunciation: "/ˌɒp.əˈtʃuː.nə.ti/", meaningVi: "cơ hội", exampleSentence: "This job is a great opportunity for me.", topicTags: ["business"], level: "B1" },
    { word: "environment", pronunciation: "/ɪnˈvaɪ.rən.mənt/", meaningVi: "môi trường", exampleSentence: "We should protect the environment.", topicTags: ["nature"], level: "B1" },
    { word: "improve", pronunciation: "/ɪmˈpruːv/", meaningVi: "cải thiện", exampleSentence: "I want to improve my English skills.", topicTags: ["verbs", "education"], level: "B1" },
    { word: "consider", pronunciation: "/kənˈsɪd.ər/", meaningVi: "cân nhắc, xem xét", exampleSentence: "Please consider my proposal carefully.", topicTags: ["business", "verbs"], level: "B1" },
    { word: "negotiate", pronunciation: "/nɪˈɡəʊ.ʃi.eɪt/", meaningVi: "đàm phán", exampleSentence: "They negotiated a better contract.", topicTags: ["business"], level: "B2" },
    {
      word: "significant",
      pronunciation: "/sɪɡˈnɪf.ɪ.kənt/",
      meaningVi: "đáng kể, quan trọng",
      exampleSentence: "There was a significant increase in sales.",
      topicTags: ["business", "adjectives"],
      level: "B2",
    },
    { word: "perspective", pronunciation: "/pəˈspek.tɪv/", meaningVi: "quan điểm, góc nhìn", exampleSentence: "Try to see it from her perspective.", topicTags: ["abstract"], level: "B2" },
    {
      word: "sustainable",
      pronunciation: "/səˈsteɪ.nə.bəl/",
      meaningVi: "bền vững",
      exampleSentence: "We need sustainable solutions for climate change.",
      topicTags: ["nature", "adjectives"],
      level: "B2",
    },
    { word: "colleague", pronunciation: "/ˈkɒl.iːɡ/", meaningVi: "đồng nghiệp", exampleSentence: "My colleague helped me finish the report.", topicTags: ["business"], level: "B1" },
    { word: "deadline", pronunciation: "/ˈded.laɪn/", meaningVi: "hạn chót", exampleSentence: "The deadline for this project is Friday.", topicTags: ["business"], level: "B1" },
    { word: "confident", pronunciation: "/ˈkɒn.fɪ.dənt/", meaningVi: "tự tin", exampleSentence: "She felt confident before the interview.", topicTags: ["adjectives", "emotions"], level: "B1" },
    { word: "flexible", pronunciation: "/ˈflek.sɪ.bəl/", meaningVi: "linh hoạt", exampleSentence: "My work schedule is very flexible.", topicTags: ["adjectives", "business"], level: "B1" },
    { word: "efficient", pronunciation: "/ɪˈfɪʃ.ənt/", meaningVi: "hiệu quả", exampleSentence: "This is a more efficient way to work.", topicTags: ["adjectives", "business"], level: "B2" },
    { word: "sunny", pronunciation: "/ˈsʌn.i/", meaningVi: "nắng, có nắng", exampleSentence: "It's sunny today.", topicTags: ["weather"], level: "A1" },
    { word: "rainy", pronunciation: "/ˈreɪ.ni/", meaningVi: "mưa, có mưa", exampleSentence: "I don't like rainy days.", topicTags: ["weather"], level: "A1" },
    { word: "cold", pronunciation: "/kəʊld/", meaningVi: "lạnh", exampleSentence: "It's very cold in winter.", topicTags: ["weather", "adjectives"], level: "A1" },
    { word: "hot", pronunciation: "/hɒt/", meaningVi: "nóng", exampleSentence: "The weather is hot in summer.", topicTags: ["weather", "adjectives"], level: "A1" },
    { word: "wind", pronunciation: "/wɪnd/", meaningVi: "gió", exampleSentence: "The wind is very strong today.", topicTags: ["weather"], level: "A2" },
    { word: "dog", pronunciation: "/dɒɡ/", meaningVi: "con chó", exampleSentence: "I have a small dog.", topicTags: ["animals"], level: "A1" },
    { word: "cat", pronunciation: "/kæt/", meaningVi: "con mèo", exampleSentence: "The cat is sleeping on the sofa.", topicTags: ["animals"], level: "A1" },
    { word: "bird", pronunciation: "/bɜːd/", meaningVi: "con chim", exampleSentence: "Birds can fly.", topicTags: ["animals"], level: "A1" },
    { word: "fish", pronunciation: "/fɪʃ/", meaningVi: "con cá", exampleSentence: "We ate fish for dinner.", topicTags: ["animals", "food"], level: "A1" },
    { word: "shirt", pronunciation: "/ʃɜːt/", meaningVi: "áo sơ mi", exampleSentence: "He is wearing a blue shirt.", topicTags: ["clothing"], level: "A1" },
    { word: "shoes", pronunciation: "/ʃuːz/", meaningVi: "giày", exampleSentence: "These shoes are very comfortable.", topicTags: ["clothing"], level: "A1" },
    { word: "jacket", pronunciation: "/ˈdʒæk.ɪt/", meaningVi: "áo khoác", exampleSentence: "Wear a jacket, it's cold outside.", topicTags: ["clothing"], level: "A1" },
    { word: "football", pronunciation: "/ˈfʊt.bɔːl/", meaningVi: "bóng đá", exampleSentence: "He plays football every weekend.", topicTags: ["sports"], level: "A1" },
    { word: "swim", pronunciation: "/swɪm/", meaningVi: "bơi", exampleSentence: "I swim every morning.", topicTags: ["sports", "verbs"], level: "A1" },
    { word: "run", pronunciation: "/rʌn/", meaningVi: "chạy", exampleSentence: "She runs five kilometers a day.", topicTags: ["sports", "verbs"], level: "A1" },
    { word: "computer", pronunciation: "/kəmˈpjuː.tər/", meaningVi: "máy tính", exampleSentence: "I use my computer for work.", topicTags: ["technology"], level: "A1" },
    { word: "internet", pronunciation: "/ˈɪn.tə.net/", meaningVi: "internet, mạng", exampleSentence: "The internet connection is slow today.", topicTags: ["technology"], level: "A1" },
    { word: "application", pronunciation: "/ˌæp.lɪˈkeɪ.ʃən/", meaningVi: "ứng dụng", exampleSentence: "I downloaded a new language learning application.", topicTags: ["technology"], level: "A2" },
    { word: "password", pronunciation: "/ˈpɑːs.wɜːd/", meaningVi: "mật khẩu", exampleSentence: "Please enter your password.", topicTags: ["technology"], level: "A2" },
    { word: "bus", pronunciation: "/bʌs/", meaningVi: "xe buýt", exampleSentence: "I take the bus to school.", topicTags: ["transport"], level: "A1" },
    { word: "train", pronunciation: "/treɪn/", meaningVi: "tàu hoả", exampleSentence: "The train leaves at 9am.", topicTags: ["transport"], level: "A1" },
    { word: "bicycle", pronunciation: "/ˈbaɪ.sɪ.kəl/", meaningVi: "xe đạp", exampleSentence: "She rides her bicycle to work.", topicTags: ["transport"], level: "A1" },
    { word: "ticket", pronunciation: "/ˈtɪk.ɪt/", meaningVi: "vé", exampleSentence: "I bought two tickets for the concert.", topicTags: ["travel"], level: "A2" },
    { word: "hotel", pronunciation: "/həʊˈtel/", meaningVi: "khách sạn", exampleSentence: "We stayed at a nice hotel.", topicTags: ["travel", "places"], level: "A2" },
    { word: "passport", pronunciation: "/ˈpɑːs.pɔːt/", meaningVi: "hộ chiếu", exampleSentence: "Don't forget your passport at the airport.", topicTags: ["travel"], level: "A2" },
    { word: "soup", pronunciation: "/suːp/", meaningVi: "súp, canh", exampleSentence: "This soup is delicious.", topicTags: ["food"], level: "A1" },
    { word: "noodle", pronunciation: "/ˈnuː.dəl/", meaningVi: "mì", exampleSentence: "I love Vietnamese noodle soup.", topicTags: ["food"], level: "A1" },
    { word: "vegetable", pronunciation: "/ˈvedʒ.tə.bəl/", meaningVi: "rau củ", exampleSentence: "You should eat more vegetables.", topicTags: ["food"], level: "A1" },
    { word: "tea", pronunciation: "/tiː/", meaningVi: "trà", exampleSentence: "My grandfather likes tea in the morning.", topicTags: ["food", "drinks"], level: "A1" },
    { word: "delicious", pronunciation: "/dɪˈlɪʃ.əs/", meaningVi: "ngon", exampleSentence: "This dish is really delicious.", topicTags: ["food", "adjectives"], level: "A2" },
    { word: "kitchen", pronunciation: "/ˈkɪtʃ.ɪn/", meaningVi: "nhà bếp", exampleSentence: "My mother is cooking in the kitchen.", topicTags: ["house"], level: "A1" },
    { word: "bedroom", pronunciation: "/ˈbed.ruːm/", meaningVi: "phòng ngủ", exampleSentence: "My bedroom is upstairs.", topicTags: ["house"], level: "A1" },
    { word: "furniture", pronunciation: "/ˈfɜː.nɪ.tʃər/", meaningVi: "đồ nội thất", exampleSentence: "We bought new furniture for the living room.", topicTags: ["house"], level: "A2" },
    { word: "garden", pronunciation: "/ˈɡɑː.dən/", meaningVi: "khu vườn", exampleSentence: "There are many flowers in the garden.", topicTags: ["house"], level: "A1" },
    { word: "doctor", pronunciation: "/ˈdɒk.tər/", meaningVi: "bác sĩ", exampleSentence: "My father is a doctor.", topicTags: ["jobs"], level: "A1" },
    { word: "engineer", pronunciation: "/ˌen.dʒɪˈnɪər/", meaningVi: "kỹ sư", exampleSentence: "She works as a software engineer.", topicTags: ["jobs"], level: "A2" },
    { word: "nurse", pronunciation: "/nɜːs/", meaningVi: "y tá", exampleSentence: "The nurse took care of the patient.", topicTags: ["jobs"], level: "A1" },
    { word: "chef", pronunciation: "/ʃef/", meaningVi: "đầu bếp", exampleSentence: "He wants to become a professional chef.", topicTags: ["jobs"], level: "A2" },
    { word: "lawyer", pronunciation: "/ˈlɔɪ.ər/", meaningVi: "luật sư", exampleSentence: "She hired a lawyer for the case.", topicTags: ["jobs"], level: "A2" },
    { word: "university", pronunciation: "/ˌjuː.nɪˈvɜː.sə.ti/", meaningVi: "trường đại học", exampleSentence: "I study at a university in Hanoi.", topicTags: ["education"], level: "A2" },
    { word: "homework", pronunciation: "/ˈhəʊm.wɜːk/", meaningVi: "bài tập về nhà", exampleSentence: "I need to finish my homework tonight.", topicTags: ["education"], level: "A1" },
    { word: "exam", pronunciation: "/ɪɡˈzæm/", meaningVi: "kỳ thi", exampleSentence: "The exam is next Monday.", topicTags: ["education"], level: "A1" },
    { word: "graduate", pronunciation: "/ˈɡrædʒ.u.eɪt/", meaningVi: "tốt nghiệp", exampleSentence: "She graduated from university last year.", topicTags: ["education", "verbs"], level: "B1" },
    { word: "headache", pronunciation: "/ˈhed.eɪk/", meaningVi: "đau đầu", exampleSentence: "I have a headache today.", topicTags: ["health"], level: "A1" },
    { word: "fever", pronunciation: "/ˈfiː.vər/", meaningVi: "sốt", exampleSentence: "My son has a fever.", topicTags: ["health"], level: "A2" },
    { word: "medicine", pronunciation: "/ˈmed.ɪ.sən/", meaningVi: "thuốc", exampleSentence: "Take this medicine twice a day.", topicTags: ["health"], level: "A2" },
    { word: "exercise", pronunciation: "/ˈek.sə.saɪz/", meaningVi: "tập thể dục", exampleSentence: "I exercise every morning.", topicTags: ["health", "verbs"], level: "A1" },
    { word: "healthy", pronunciation: "/ˈhel.θi/", meaningVi: "khoẻ mạnh", exampleSentence: "Eating vegetables keeps you healthy.", topicTags: ["health", "adjectives"], level: "A1" },
    { word: "appointment", pronunciation: "/əˈpɔɪnt.mənt/", meaningVi: "cuộc hẹn", exampleSentence: "I have a doctor's appointment tomorrow.", topicTags: ["health", "business"], level: "B1" },
    { word: "discount", pronunciation: "/ˈdɪs.kaʊnt/", meaningVi: "giảm giá", exampleSentence: "This shirt has a 20% discount.", topicTags: ["shopping"], level: "A2" },
    { word: "receipt", pronunciation: "/rɪˈsiːt/", meaningVi: "hoá đơn", exampleSentence: "Please keep the receipt.", topicTags: ["shopping"], level: "A2" },
    { word: "size", pronunciation: "/saɪz/", meaningVi: "kích cỡ", exampleSentence: "Do you have this in a bigger size?", topicTags: ["shopping"], level: "A1" },
    { word: "excited", pronunciation: "/ɪkˈsaɪ.tɪd/", meaningVi: "hào hứng", exampleSentence: "I'm so excited about the trip.", topicTags: ["emotions", "adjectives"], level: "A1" },
    { word: "nervous", pronunciation: "/ˈnɜː.vəs/", meaningVi: "lo lắng, hồi hộp", exampleSentence: "She felt nervous before the exam.", topicTags: ["emotions", "adjectives"], level: "A2" },
    { word: "disappointed", pronunciation: "/ˌdɪs.əˈpɔɪn.tɪd/", meaningVi: "thất vọng", exampleSentence: "I was disappointed with the result.", topicTags: ["emotions", "adjectives"], level: "B1" },
    { word: "bored", pronunciation: "/bɔːd/", meaningVi: "chán", exampleSentence: "I'm bored, let's do something fun.", topicTags: ["emotions", "adjectives"], level: "A1" },
    { word: "reading", pronunciation: "/ˈriː.dɪŋ/", meaningVi: "đọc sách (sở thích)", exampleSentence: "My hobby is reading books.", topicTags: ["hobbies"], level: "A1" },
    { word: "painting", pronunciation: "/ˈpeɪn.tɪŋ/", meaningVi: "vẽ tranh", exampleSentence: "She enjoys painting in her free time.", topicTags: ["hobbies"], level: "A2" },
    { word: "photography", pronunciation: "/fəˈtɒɡ.rə.fi/", meaningVi: "nhiếp ảnh", exampleSentence: "Photography is his passion.", topicTags: ["hobbies"], level: "B1" },
    { word: "gardening", pronunciation: "/ˈɡɑː.dən.ɪŋ/", meaningVi: "làm vườn", exampleSentence: "My grandmother loves gardening.", topicTags: ["hobbies"], level: "A2" },
    { word: "street", pronunciation: "/striːt/", meaningVi: "đường phố", exampleSentence: "Turn left on this street.", topicTags: ["city", "directions"], level: "A1" },
    { word: "corner", pronunciation: "/ˈkɔː.nər/", meaningVi: "góc, ngã tư", exampleSentence: "The cafe is on the corner.", topicTags: ["city", "directions"], level: "A2" },
    { word: "straight", pronunciation: "/streɪt/", meaningVi: "thẳng", exampleSentence: "Go straight for two blocks.", topicTags: ["directions"], level: "A2" },
    { word: "traffic", pronunciation: "/ˈtræf.ɪk/", meaningVi: "giao thông, tắc đường", exampleSentence: "There is a lot of traffic this morning.", topicTags: ["city"], level: "A2" },
    { word: "crowded", pronunciation: "/ˈkraʊ.dɪd/", meaningVi: "đông đúc", exampleSentence: "The market is very crowded on weekends.", topicTags: ["city", "adjectives"], level: "B1" },
    { word: "century", pronunciation: "/ˈsen.tʃər.i/", meaningVi: "thế kỷ", exampleSentence: "This building was built in the 19th century.", topicTags: ["time"], level: "B1" },
    { word: "recently", pronunciation: "/ˈriː.sənt.li/", meaningVi: "gần đây", exampleSentence: "I haven't seen him recently.", topicTags: ["time"], level: "B1" },
    { word: "eventually", pronunciation: "/ɪˈven.tʃu.ə.li/", meaningVi: "cuối cùng", exampleSentence: "Eventually, we found the right way.", topicTags: ["time"], level: "B1" },
    { word: "immediately", pronunciation: "/ɪˈmiː.di.ət.li/", meaningVi: "ngay lập tức", exampleSentence: "Please call me immediately.", topicTags: ["time"], level: "B1" },
    { word: "punctual", pronunciation: "/ˈpʌŋk.tʃu.əl/", meaningVi: "đúng giờ", exampleSentence: "He is always punctual for meetings.", topicTags: ["time", "adjectives"], level: "B2" },
    { word: "postpone", pronunciation: "/pəˈspəʊn/", meaningVi: "hoãn lại", exampleSentence: "We had to postpone the meeting.", topicTags: ["business", "verbs"], level: "B1" },
    { word: "attend", pronunciation: "/əˈtend/", meaningVi: "tham dự", exampleSentence: "I will attend the conference next week.", topicTags: ["business", "verbs"], level: "B1" },
    { word: "invite", pronunciation: "/ɪnˈvaɪt/", meaningVi: "mời", exampleSentence: "She invited me to her birthday party.", topicTags: ["verbs", "daily"], level: "A2" },
    { word: "head", pronunciation: "/hed/", meaningVi: "đầu", exampleSentence: "My head hurts.", topicTags: ["body"], level: "A1" },
    { word: "hand", pronunciation: "/hænd/", meaningVi: "tay", exampleSentence: "Wash your hands before eating.", topicTags: ["body"], level: "A1" },
    { word: "leg", pronunciation: "/leɡ/", meaningVi: "chân", exampleSentence: "He broke his leg last month.", topicTags: ["body"], level: "A1" },
    { word: "eye", pronunciation: "/aɪ/", meaningVi: "mắt", exampleSentence: "She has beautiful eyes.", topicTags: ["body"], level: "A1" },
    { word: "heart", pronunciation: "/hɑːt/", meaningVi: "tim, trái tim", exampleSentence: "Exercise is good for your heart.", topicTags: ["body", "health"], level: "A1" },
    { word: "grandmother", pronunciation: "/ˈɡræn.mʌð.ər/", meaningVi: "bà", exampleSentence: "My grandmother tells great stories.", topicTags: ["family"], level: "A1" },
    { word: "grandfather", pronunciation: "/ˈɡræn.fɑː.ðər/", meaningVi: "ông", exampleSentence: "My grandfather is 80 years old.", topicTags: ["family"], level: "A1" },
    { word: "sibling", pronunciation: "/ˈsɪb.lɪŋ/", meaningVi: "anh chị em ruột", exampleSentence: "I have two siblings.", topicTags: ["family"], level: "A2" },
    { word: "cousin", pronunciation: "/ˈkʌz.ən/", meaningVi: "anh chị em họ", exampleSentence: "My cousin lives in Saigon.", topicTags: ["family"], level: "A2" },
    { word: "spring", pronunciation: "/sprɪŋ/", meaningVi: "mùa xuân", exampleSentence: "Flowers bloom in spring.", topicTags: ["seasons"], level: "A1" },
    { word: "summer", pronunciation: "/ˈsʌm.ər/", meaningVi: "mùa hè", exampleSentence: "We go swimming in summer.", topicTags: ["seasons"], level: "A1" },
    { word: "autumn", pronunciation: "/ˈɔː.təm/", meaningVi: "mùa thu", exampleSentence: "The leaves fall in autumn.", topicTags: ["seasons"], level: "A1" },
    { word: "winter", pronunciation: "/ˈwɪn.tər/", meaningVi: "mùa đông", exampleSentence: "It snows in winter.", topicTags: ["seasons"], level: "A1" },
    { word: "January", pronunciation: "/ˈdʒæn.ju.ər.i/", meaningVi: "tháng Một", exampleSentence: "My birthday is in January.", topicTags: ["calendar"], level: "A1" },
    { word: "wallet", pronunciation: "/ˈwɒl.ɪt/", meaningVi: "ví tiền", exampleSentence: "I lost my wallet yesterday.", topicTags: ["finance"], level: "A1" },
    { word: "bank", pronunciation: "/bæŋk/", meaningVi: "ngân hàng", exampleSentence: "I need to go to the bank.", topicTags: ["finance", "places"], level: "A1" },
    { word: "save", pronunciation: "/seɪv/", meaningVi: "tiết kiệm", exampleSentence: "I try to save money every month.", topicTags: ["finance", "verbs"], level: "A2" },
    { word: "salary", pronunciation: "/ˈsæl.ər.i/", meaningVi: "lương", exampleSentence: "Her salary increased this year.", topicTags: ["finance", "business"], level: "B1" },
    { word: "expensive", pronunciation: "/ɪkˈspen.sɪv/", meaningVi: "đắt", exampleSentence: "This restaurant is too expensive.", topicTags: ["finance", "adjectives"], level: "A1" },
    { word: "budget", pronunciation: "/ˈbʌdʒ.ɪt/", meaningVi: "ngân sách", exampleSentence: "We need to plan our budget carefully.", topicTags: ["finance", "business"], level: "B1" },
    { word: "loan", pronunciation: "/ləʊn/", meaningVi: "khoản vay", exampleSentence: "They took out a loan to buy a house.", topicTags: ["finance"], level: "B1" },
    { word: "credit card", pronunciation: "/ˈkred.ɪt kɑːd/", meaningVi: "thẻ tín dụng", exampleSentence: "I paid with my credit card.", topicTags: ["finance", "shopping"], level: "A2" },
    { word: "cash", pronunciation: "/kæʃ/", meaningVi: "tiền mặt", exampleSentence: "Do you accept cash?", topicTags: ["finance", "shopping"], level: "A1" },
    { word: "income", pronunciation: "/ˈɪŋ.kʌm/", meaningVi: "thu nhập", exampleSentence: "His monthly income is stable.", topicTags: ["finance", "business"], level: "B1" },
    { word: "kind", pronunciation: "/kaɪnd/", meaningVi: "tốt bụng", exampleSentence: "She is very kind to everyone.", topicTags: ["personality", "adjectives"], level: "A1" },
    { word: "funny", pronunciation: "/ˈfʌn.i/", meaningVi: "hài hước", exampleSentence: "My brother is really funny.", topicTags: ["personality", "adjectives"], level: "A1" },
    { word: "smart", pronunciation: "/smɑːt/", meaningVi: "thông minh", exampleSentence: "She is the smartest student in class.", topicTags: ["personality", "adjectives"], level: "A1" },
    { word: "honest", pronunciation: "/ˈɒn.ɪst/", meaningVi: "trung thực", exampleSentence: "He is always honest with me.", topicTags: ["personality", "adjectives"], level: "A2" },
    { word: "lazy", pronunciation: "/ˈleɪ.zi/", meaningVi: "lười biếng", exampleSentence: "Don't be lazy, finish your homework.", topicTags: ["personality", "adjectives"], level: "A1" },
    { word: "wake up", pronunciation: "/weɪk ʌp/", meaningVi: "thức dậy", exampleSentence: "I wake up at 6am every day.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "brush teeth", pronunciation: "/brʌʃ tiːθ/", meaningVi: "đánh răng", exampleSentence: "I brush my teeth twice a day.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "take a shower", pronunciation: "/teɪk ə ˈʃaʊər/", meaningVi: "tắm", exampleSentence: "I take a shower every morning.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "get dressed", pronunciation: "/ɡet drest/", meaningVi: "mặc quần áo", exampleSentence: "She gets dressed quickly.", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "cook", pronunciation: "/kʊk/", meaningVi: "nấu ăn", exampleSentence: "My father cooks dinner every Friday.", topicTags: ["daily", "verbs", "food"], level: "A1" },
    { word: "who", pronunciation: "/huː/", meaningVi: "ai", exampleSentence: "Who is that person?", topicTags: ["questions"], level: "A1" },
    { word: "what", pronunciation: "/wɒt/", meaningVi: "cái gì", exampleSentence: "What is your name?", topicTags: ["questions"], level: "A1" },
    { word: "where", pronunciation: "/weər/", meaningVi: "ở đâu", exampleSentence: "Where do you live?", topicTags: ["questions"], level: "A1" },
    { word: "when", pronunciation: "/wen/", meaningVi: "khi nào", exampleSentence: "When is your birthday?", topicTags: ["questions"], level: "A1" },
    { word: "why", pronunciation: "/waɪ/", meaningVi: "tại sao", exampleSentence: "Why are you late?", topicTags: ["questions"], level: "A1" },
    { word: "mountain", pronunciation: "/ˈmaʊn.tɪn/", meaningVi: "núi", exampleSentence: "We climbed the mountain last weekend.", topicTags: ["nature"], level: "A1" },
    { word: "sea", pronunciation: "/siː/", meaningVi: "biển", exampleSentence: "I love swimming in the sea.", topicTags: ["nature"], level: "A1" },
    { word: "forest", pronunciation: "/ˈfɒr.ɪst/", meaningVi: "rừng", exampleSentence: "There are many animals in the forest.", topicTags: ["nature"], level: "A2" },
    { word: "sky", pronunciation: "/skaɪ/", meaningVi: "bầu trời", exampleSentence: "The sky is blue today.", topicTags: ["nature"], level: "A1" },
    { word: "tree", pronunciation: "/triː/", meaningVi: "cây", exampleSentence: "There is a big tree in front of my house.", topicTags: ["nature"], level: "A1" },
    { word: "knife", pronunciation: "/naɪf/", meaningVi: "con dao", exampleSentence: "Be careful with that knife.", topicTags: ["kitchen"], level: "A1" },
    { word: "fork", pronunciation: "/fɔːk/", meaningVi: "cái nĩa", exampleSentence: "Can I have a fork, please?", topicTags: ["kitchen"], level: "A1" },
    { word: "plate", pronunciation: "/pleɪt/", meaningVi: "cái đĩa", exampleSentence: "Put the food on the plate.", topicTags: ["kitchen"], level: "A1" },
    { word: "easy", pronunciation: "/ˈiː.zi/", meaningVi: "dễ", exampleSentence: "This exercise is very easy.", topicTags: ["adjectives"], level: "A1" },
    { word: "difficult", pronunciation: "/ˈdɪf.ɪ.kəlt/", meaningVi: "khó", exampleSentence: "This question is too difficult for me.", topicTags: ["adjectives"], level: "A1" },
  ];

  for (const word of englishWords) {
    await prisma.vocabularyCard.upsert({
      where: {
        // upsert theo word + languageId để tránh duplicate
        id: `en-${word.word}`,
      },
      update: {},
      create: {
        id: `en-${word.word}`,
        languageId: enLang.id,
        word: word.word,
        pronunciation: word.pronunciation,
        meaningVi: word.meaningVi,
        exampleSentence: word.exampleSentence,
        topicTags: word.topicTags,
        level: word.level as any,
      },
    });
  }

  // ─── Tiếng Trung A1 (mẫu 10 từ) ──────────────────────────────────────────────
  const chineseWords = [
    { word: "你好", pronunciation: "nǐ hǎo", meaningVi: "xin chào", exampleSentence: "你好，很高兴认识你。(Xin chào, rất vui được gặp bạn.)", topicTags: ["greetings"], level: "A1" },
    { word: "谢谢", pronunciation: "xiè xiè", meaningVi: "cảm ơn", exampleSentence: "谢谢你的帮助。(Cảm ơn sự giúp đỡ của bạn.)", topicTags: ["greetings", "daily"], level: "A1" },
    { word: "再见", pronunciation: "zài jiàn", meaningVi: "tạm biệt", exampleSentence: "明天见，再见！(Hẹn gặp ngày mai, tạm biệt!)", topicTags: ["greetings"], level: "A1" },
    { word: "水", pronunciation: "shuǐ", meaningVi: "nước", exampleSentence: "我要喝水。(Tôi muốn uống nước.)", topicTags: ["food", "daily"], level: "A1" },
    { word: "吃饭", pronunciation: "chī fàn", meaningVi: "ăn cơm", exampleSentence: "我们去吃饭吧。(Chúng ta đi ăn cơm thôi.)", topicTags: ["food", "daily"], level: "A1" },
    { word: "朋友", pronunciation: "péng yǒu", meaningVi: "bạn bè", exampleSentence: "他是我的好朋友。(Anh ấy là bạn tốt của tôi.)", topicTags: ["family", "daily"], level: "A1" },
    { word: "家", pronunciation: "jiā", meaningVi: "nhà, gia đình", exampleSentence: "我回家了。(Tôi về nhà rồi.)", topicTags: ["home", "family"], level: "A1" },
    { word: "工作", pronunciation: "gōng zuò", meaningVi: "công việc, làm việc", exampleSentence: "我喜欢我的工作。(Tôi thích công việc của mình.)", topicTags: ["work", "daily"], level: "A1" },
    { word: "学习", pronunciation: "xué xí", meaningVi: "học tập", exampleSentence: "我每天学习中文。(Tôi học tiếng Trung mỗi ngày.)", topicTags: ["education"], level: "A1" },
    { word: "喜欢", pronunciation: "xǐ huān", meaningVi: "thích", exampleSentence: "我喜欢吃越南菜。(Tôi thích ăn món Việt.)", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "一", pronunciation: "yī", meaningVi: "một", exampleSentence: "我有一个苹果。(Tôi có một quả táo.)", topicTags: ["numbers"], level: "A1" },
    { word: "二", pronunciation: "èr", meaningVi: "hai", exampleSentence: "我有二个朋友。(Tôi có hai người bạn.)", topicTags: ["numbers"], level: "A1" },
    { word: "三", pronunciation: "sān", meaningVi: "ba", exampleSentence: "现在三点了。(Bây giờ là 3 giờ rồi.)", topicTags: ["numbers"], level: "A1" },
    { word: "红色", pronunciation: "hóng sè", meaningVi: "màu đỏ", exampleSentence: "我喜欢红色。(Tôi thích màu đỏ.)", topicTags: ["colors"], level: "A1" },
    { word: "蓝色", pronunciation: "lán sè", meaningVi: "màu xanh dương", exampleSentence: "天空是蓝色的。(Bầu trời màu xanh.)", topicTags: ["colors"], level: "A1" },
    { word: "妈妈", pronunciation: "mā ma", meaningVi: "mẹ", exampleSentence: "我妈妈是老师。(Mẹ tôi là giáo viên.)", topicTags: ["family"], level: "A1" },
    { word: "爸爸", pronunciation: "bà ba", meaningVi: "bố", exampleSentence: "我爸爸喜欢喝茶。(Bố tôi thích uống trà.)", topicTags: ["family"], level: "A1" },
    { word: "今天", pronunciation: "jīn tiān", meaningVi: "hôm nay", exampleSentence: "今天天气很好。(Hôm nay thời tiết đẹp.)", topicTags: ["time"], level: "A1" },
    { word: "明天", pronunciation: "míng tiān", meaningVi: "ngày mai", exampleSentence: "明天我要去学校。(Ngày mai tôi phải đi học.)", topicTags: ["time"], level: "A1" },
    { word: "时间", pronunciation: "shí jiān", meaningVi: "thời gian", exampleSentence: "我没有时间。(Tôi không có thời gian.)", topicTags: ["time"], level: "A2" },
    { word: "旅行", pronunciation: "lǚ xíng", meaningVi: "du lịch", exampleSentence: "我们下个月去旅行。(Tháng sau chúng tôi đi du lịch.)", topicTags: ["travel"], level: "A2" },
    { word: "飞机", pronunciation: "fēi jī", meaningVi: "máy bay", exampleSentence: "我坐飞机去中国。(Tôi đi máy bay đến Trung Quốc.)", topicTags: ["travel"], level: "A2" },
    { word: "医院", pronunciation: "yī yuàn", meaningVi: "bệnh viện", exampleSentence: "他在医院工作。(Anh ấy làm việc ở bệnh viện.)", topicTags: ["places"], level: "A2" },
    { word: "便宜", pronunciation: "pián yi", meaningVi: "rẻ", exampleSentence: "这个手机很便宜。(Cái điện thoại này rất rẻ.)", topicTags: ["shopping", "adjectives"], level: "A2" },
    { word: "职业", pronunciation: "zhí yè", meaningVi: "nghề nghiệp", exampleSentence: "你的职业是什么？(Nghề nghiệp của bạn là gì?)", topicTags: ["business"], level: "B1" },
    { word: "经验", pronunciation: "jīng yàn", meaningVi: "kinh nghiệm", exampleSentence: "他有很多工作经验。(Anh ấy có nhiều kinh nghiệm làm việc.)", topicTags: ["business"], level: "B1" },
    { word: "机会", pronunciation: "jī huì", meaningVi: "cơ hội", exampleSentence: "这是一个好机会。(Đây là một cơ hội tốt.)", topicTags: ["business"], level: "B1" },
    { word: "环境", pronunciation: "huán jìng", meaningVi: "môi trường", exampleSentence: "我们要保护环境。(Chúng ta phải bảo vệ môi trường.)", topicTags: ["nature"], level: "B1" },
    { word: "解决", pronunciation: "jiě jué", meaningVi: "giải quyết", exampleSentence: "我们需要解决这个问题。(Chúng ta cần giải quyết vấn đề này.)", topicTags: ["verbs", "business"], level: "B1" },
    { word: "同事", pronunciation: "tóng shì", meaningVi: "đồng nghiệp", exampleSentence: "我的同事很友好。(Đồng nghiệp của tôi rất thân thiện.)", topicTags: ["business"], level: "B1" },
    { word: "自信", pronunciation: "zì xìn", meaningVi: "tự tin", exampleSentence: "面试的时候要自信。(Lúc phỏng vấn phải tự tin.)", topicTags: ["adjectives", "emotions"], level: "B1" },
    { word: "压力", pronunciation: "yā lì", meaningVi: "áp lực, căng thẳng", exampleSentence: "工作压力很大。(Áp lực công việc rất lớn.)", topicTags: ["emotions", "business"], level: "B1" },
    { word: "成功", pronunciation: "chéng gōng", meaningVi: "thành công", exampleSentence: "他终于成功了。(Cuối cùng anh ấy đã thành công.)", topicTags: ["abstract"], level: "B1" },
    { word: "决定", pronunciation: "jué dìng", meaningVi: "quyết định", exampleSentence: "这是一个重要的决定。(Đây là một quyết định quan trọng.)", topicTags: ["abstract", "business"], level: "B1" },
    { word: "晴天", pronunciation: "qíng tiān", meaningVi: "trời nắng", exampleSentence: "今天是晴天。(Hôm nay trời nắng.)", topicTags: ["weather"], level: "A1" },
    { word: "下雨", pronunciation: "xià yǔ", meaningVi: "trời mưa", exampleSentence: "外面在下雨。(Bên ngoài đang mưa.)", topicTags: ["weather"], level: "A1" },
    { word: "冷", pronunciation: "lěng", meaningVi: "lạnh", exampleSentence: "冬天很冷。(Mùa đông rất lạnh.)", topicTags: ["weather", "adjectives"], level: "A1" },
    { word: "热", pronunciation: "rè", meaningVi: "nóng", exampleSentence: "夏天很热。(Mùa hè rất nóng.)", topicTags: ["weather", "adjectives"], level: "A1" },
    { word: "狗", pronunciation: "gǒu", meaningVi: "con chó", exampleSentence: "我有一只小狗。(Tôi có một con chó nhỏ.)", topicTags: ["animals"], level: "A1" },
    { word: "猫", pronunciation: "māo", meaningVi: "con mèo", exampleSentence: "猫在睡觉。(Con mèo đang ngủ.)", topicTags: ["animals"], level: "A1" },
    { word: "鸟", pronunciation: "niǎo", meaningVi: "con chim", exampleSentence: "鸟会飞。(Chim biết bay.)", topicTags: ["animals"], level: "A1" },
    { word: "鱼", pronunciation: "yú", meaningVi: "con cá", exampleSentence: "我们晚饭吃鱼。(Chúng tôi ăn cá cho bữa tối.)", topicTags: ["animals", "food"], level: "A1" },
    { word: "衬衫", pronunciation: "chèn shān", meaningVi: "áo sơ mi", exampleSentence: "他穿蓝色的衬衫。(Anh ấy mặc áo sơ mi màu xanh.)", topicTags: ["clothing"], level: "A1" },
    { word: "鞋子", pronunciation: "xié zi", meaningVi: "giày", exampleSentence: "这双鞋子很舒服。(Đôi giày này rất thoải mái.)", topicTags: ["clothing"], level: "A1" },
    { word: "足球", pronunciation: "zú qiú", meaningVi: "bóng đá", exampleSentence: "他每个周末踢足球。(Anh ấy đá bóng mỗi cuối tuần.)", topicTags: ["sports"], level: "A1" },
    { word: "游泳", pronunciation: "yóu yǒng", meaningVi: "bơi lội", exampleSentence: "我每天早上游泳。(Tôi bơi mỗi sáng.)", topicTags: ["sports", "verbs"], level: "A1" },
    { word: "跑步", pronunciation: "pǎo bù", meaningVi: "chạy bộ", exampleSentence: "她每天跑步五公里。(Cô ấy chạy bộ 5km mỗi ngày.)", topicTags: ["sports", "verbs"], level: "A1" },
    { word: "电脑", pronunciation: "diàn nǎo", meaningVi: "máy tính", exampleSentence: "我用电脑工作。(Tôi dùng máy tính để làm việc.)", topicTags: ["technology"], level: "A1" },
    { word: "网络", pronunciation: "wǎng luò", meaningVi: "internet, mạng", exampleSentence: "今天网络很慢。(Hôm nay mạng rất chậm.)", topicTags: ["technology"], level: "A1" },
    { word: "手机", pronunciation: "shǒu jī", meaningVi: "điện thoại di động", exampleSentence: "我的手机是新的。(Điện thoại của tôi là mới.)", topicTags: ["technology"], level: "A1" },
    { word: "密码", pronunciation: "mì mǎ", meaningVi: "mật khẩu", exampleSentence: "请输入密码。(Vui lòng nhập mật khẩu.)", topicTags: ["technology"], level: "A2" },
    { word: "公共汽车", pronunciation: "gōnggòng qìchē", meaningVi: "xe buýt", exampleSentence: "我坐公共汽车去学校。(Tôi đi xe buýt đến trường.)", topicTags: ["transport"], level: "A1" },
    { word: "火车", pronunciation: "huǒ chē", meaningVi: "tàu hoả", exampleSentence: "火车九点出发。(Tàu khởi hành lúc 9 giờ.)", topicTags: ["transport"], level: "A1" },
    { word: "自行车", pronunciation: "zì xíng chē", meaningVi: "xe đạp", exampleSentence: "她骑自行车上班。(Cô ấy đi xe đạp đi làm.)", topicTags: ["transport"], level: "A1" },
    { word: "票", pronunciation: "piào", meaningVi: "vé", exampleSentence: "我买了两张票。(Tôi đã mua hai vé.)", topicTags: ["travel"], level: "A2" },
    { word: "酒店", pronunciation: "jiǔ diàn", meaningVi: "khách sạn", exampleSentence: "我们住在一家好酒店。(Chúng tôi ở một khách sạn tốt.)", topicTags: ["travel", "places"], level: "A2" },
    { word: "护照", pronunciation: "hù zhào", meaningVi: "hộ chiếu", exampleSentence: "在机场别忘了带护照。(Đừng quên mang hộ chiếu ở sân bay.)", topicTags: ["travel"], level: "A2" },
    { word: "米饭", pronunciation: "mǐ fàn", meaningVi: "cơm", exampleSentence: "我们每天吃米饭。(Chúng tôi ăn cơm mỗi ngày.)", topicTags: ["food"], level: "A1" },
    { word: "面条", pronunciation: "miàn tiáo", meaningVi: "mì", exampleSentence: "我喜欢吃越南面条。(Tôi thích ăn mì Việt Nam.)", topicTags: ["food"], level: "A1" },
    { word: "蔬菜", pronunciation: "shū cài", meaningVi: "rau củ", exampleSentence: "你应该多吃蔬菜。(Bạn nên ăn nhiều rau hơn.)", topicTags: ["food"], level: "A1" },
    { word: "咖啡", pronunciation: "kā fēi", meaningVi: "cà phê", exampleSentence: "我每天早上喝咖啡。(Tôi uống cà phê mỗi sáng.)", topicTags: ["food", "drinks"], level: "A1" },
    { word: "好吃", pronunciation: "hǎo chī", meaningVi: "ngon", exampleSentence: "这道菜很好吃。(Món này rất ngon.)", topicTags: ["food", "adjectives"], level: "A1" },
    { word: "厨房", pronunciation: "chú fáng", meaningVi: "nhà bếp", exampleSentence: "妈妈在厨房做饭。(Mẹ đang nấu ăn trong bếp.)", topicTags: ["house"], level: "A1" },
    { word: "卧室", pronunciation: "wò shì", meaningVi: "phòng ngủ", exampleSentence: "我的卧室在楼上。(Phòng ngủ của tôi ở trên lầu.)", topicTags: ["house"], level: "A1" },
    { word: "花园", pronunciation: "huā yuán", meaningVi: "khu vườn", exampleSentence: "花园里有很多花。(Trong vườn có nhiều hoa.)", topicTags: ["house"], level: "A1" },
    { word: "医生", pronunciation: "yī shēng", meaningVi: "bác sĩ", exampleSentence: "我爸爸是医生。(Bố tôi là bác sĩ.)", topicTags: ["jobs"], level: "A1" },
    { word: "工程师", pronunciation: "gōng chéng shī", meaningVi: "kỹ sư", exampleSentence: "她是软件工程师。(Cô ấy là kỹ sư phần mềm.)", topicTags: ["jobs"], level: "A2" },
    { word: "护士", pronunciation: "hù shì", meaningVi: "y tá", exampleSentence: "护士照顾病人。(Y tá chăm sóc bệnh nhân.)", topicTags: ["jobs"], level: "A1" },
    { word: "厨师", pronunciation: "chú shī", meaningVi: "đầu bếp", exampleSentence: "他想成为专业厨师。(Anh ấy muốn trở thành đầu bếp chuyên nghiệp.)", topicTags: ["jobs"], level: "A2" },
    { word: "律师", pronunciation: "lǜ shī", meaningVi: "luật sư", exampleSentence: "她请了一位律师。(Cô ấy đã thuê một luật sư.)", topicTags: ["jobs"], level: "A2" },
    { word: "大学", pronunciation: "dà xué", meaningVi: "trường đại học", exampleSentence: "我在河内的大学学习。(Tôi học ở một trường đại học tại Hà Nội.)", topicTags: ["education"], level: "A2" },
    { word: "作业", pronunciation: "zuò yè", meaningVi: "bài tập về nhà", exampleSentence: "我今晚要写作业。(Tối nay tôi phải làm bài tập.)", topicTags: ["education"], level: "A1" },
    { word: "考试", pronunciation: "kǎo shì", meaningVi: "kỳ thi", exampleSentence: "考试是下周一。(Kỳ thi là thứ Hai tuần sau.)", topicTags: ["education"], level: "A1" },
    { word: "毕业", pronunciation: "bì yè", meaningVi: "tốt nghiệp", exampleSentence: "她去年毕业了。(Cô ấy đã tốt nghiệp năm ngoái.)", topicTags: ["education", "verbs"], level: "B1" },
    { word: "头疼", pronunciation: "tóu téng", meaningVi: "đau đầu", exampleSentence: "我今天头疼。(Hôm nay tôi bị đau đầu.)", topicTags: ["health"], level: "A1" },
    { word: "发烧", pronunciation: "fā shāo", meaningVi: "sốt", exampleSentence: "我儿子发烧了。(Con trai tôi bị sốt.)", topicTags: ["health"], level: "A2" },
    { word: "药", pronunciation: "yào", meaningVi: "thuốc", exampleSentence: "一天吃两次药。(Uống thuốc 2 lần một ngày.)", topicTags: ["health"], level: "A2" },
    { word: "锻炼", pronunciation: "duàn liàn", meaningVi: "tập thể dục", exampleSentence: "我每天早上锻炼。(Tôi tập thể dục mỗi sáng.)", topicTags: ["health", "verbs"], level: "A1" },
    { word: "健康", pronunciation: "jiàn kāng", meaningVi: "khoẻ mạnh", exampleSentence: "吃蔬菜对健康有好处。(Ăn rau tốt cho sức khoẻ.)", topicTags: ["health", "adjectives"], level: "A1" },
    { word: "预约", pronunciation: "yù yuē", meaningVi: "cuộc hẹn", exampleSentence: "我明天有医生预约。(Ngày mai tôi có hẹn với bác sĩ.)", topicTags: ["health", "business"], level: "B1" },
    { word: "打折", pronunciation: "dǎ zhé", meaningVi: "giảm giá", exampleSentence: "这件衣服打折了。(Cái áo này được giảm giá.)", topicTags: ["shopping"], level: "A2" },
    { word: "发票", pronunciation: "fā piào", meaningVi: "hoá đơn", exampleSentence: "请保留发票。(Vui lòng giữ hoá đơn.)", topicTags: ["shopping"], level: "A2" },
    { word: "尺寸", pronunciation: "chǐ cùn", meaningVi: "kích cỡ", exampleSentence: "有大一点的尺寸吗？(Có kích cỡ lớn hơn không?)", topicTags: ["shopping"], level: "A1" },
    { word: "兴奋", pronunciation: "xīng fèn", meaningVi: "hào hứng", exampleSentence: "我对这次旅行很兴奋。(Tôi rất hào hứng về chuyến đi này.)", topicTags: ["emotions", "adjectives"], level: "A1" },
    {
      word: "紧张",
      pronunciation: "jǐn zhāng",
      meaningVi: "lo lắng, hồi hộp",
      exampleSentence: "考试前她很紧张。(Trước kỳ thi cô ấy rất hồi hộp.)",
      topicTags: ["emotions", "adjectives"],
      level: "A2",
    },
    { word: "失望", pronunciation: "shī wàng", meaningVi: "thất vọng", exampleSentence: "我对结果很失望。(Tôi rất thất vọng về kết quả.)", topicTags: ["emotions", "adjectives"], level: "B1" },
    { word: "无聊", pronunciation: "wú liáo", meaningVi: "chán", exampleSentence: "我很无聊，我们做点有趣的事吧。(Tôi thấy chán, làm gì vui đi.)", topicTags: ["emotions", "adjectives"], level: "A1" },
    { word: "阅读", pronunciation: "yuè dú", meaningVi: "đọc sách (sở thích)", exampleSentence: "我的爱好是阅读。(Sở thích của tôi là đọc sách.)", topicTags: ["hobbies"], level: "A1" },
    { word: "画画", pronunciation: "huà huà", meaningVi: "vẽ tranh", exampleSentence: "她喜欢在空闲时间画画。(Cô ấy thích vẽ tranh lúc rảnh.)", topicTags: ["hobbies"], level: "A2" },
    { word: "摄影", pronunciation: "shè yǐng", meaningVi: "nhiếp ảnh", exampleSentence: "摄影是他的爱好。(Nhiếp ảnh là đam mê của anh ấy.)", topicTags: ["hobbies"], level: "B1" },
    { word: "街道", pronunciation: "jiē dào", meaningVi: "đường phố", exampleSentence: "在这条街左转。(Rẽ trái ở đường này.)", topicTags: ["city", "directions"], level: "A1" },
    { word: "拐角", pronunciation: "guǎi jiǎo", meaningVi: "góc, ngã tư", exampleSentence: "咖啡馆在拐角处。(Quán cà phê ở góc đường.)", topicTags: ["city", "directions"], level: "A2" },
    { word: "一直", pronunciation: "yì zhí", meaningVi: "đi thẳng, luôn luôn", exampleSentence: "一直走两个路口。(Đi thẳng qua 2 ngã tư.)", topicTags: ["directions"], level: "A2" },
    { word: "交通", pronunciation: "jiāo tōng", meaningVi: "giao thông", exampleSentence: "今天早上交通很拥堵。(Sáng nay giao thông rất tắc.)", topicTags: ["city"], level: "A2" },
    { word: "拥挤", pronunciation: "yōng jǐ", meaningVi: "đông đúc", exampleSentence: "周末市场很拥挤。(Cuối tuần chợ rất đông đúc.)", topicTags: ["city", "adjectives"], level: "B1" },
    { word: "世纪", pronunciation: "shì jì", meaningVi: "thế kỷ", exampleSentence: "这座建筑建于19世纪。(Toà nhà này được xây vào thế kỷ 19.)", topicTags: ["time"], level: "B1" },
    { word: "最近", pronunciation: "zuì jìn", meaningVi: "gần đây", exampleSentence: "我最近没见到他。(Gần đây tôi không gặp anh ấy.)", topicTags: ["time"], level: "B1" },
    { word: "终于", pronunciation: "zhōng yú", meaningVi: "cuối cùng", exampleSentence: "我们终于找到了正确的路。(Cuối cùng chúng tôi cũng tìm ra đường đúng.)", topicTags: ["time"], level: "B1" },
    { word: "马上", pronunciation: "mǎ shàng", meaningVi: "ngay lập tức", exampleSentence: "请马上给我打电话。(Hãy gọi cho tôi ngay lập tức.)", topicTags: ["time"], level: "B1" },
    { word: "推迟", pronunciation: "tuī chí", meaningVi: "hoãn lại", exampleSentence: "我们不得不推迟会议。(Chúng tôi phải hoãn cuộc họp.)", topicTags: ["business", "verbs"], level: "B1" },
    { word: "参加", pronunciation: "cān jiā", meaningVi: "tham dự", exampleSentence: "我下周会参加会议。(Tuần sau tôi sẽ tham dự hội nghị.)", topicTags: ["business", "verbs"], level: "B1" },
    { word: "邀请", pronunciation: "yāo qǐng", meaningVi: "mời", exampleSentence: "她邀请我参加她的生日派对。(Cô ấy mời tôi dự tiệc sinh nhật.)", topicTags: ["verbs", "daily"], level: "A2" },
    { word: "头", pronunciation: "tóu", meaningVi: "đầu", exampleSentence: "我的头很疼。(Đầu tôi rất đau.)", topicTags: ["body"], level: "A1" },
    { word: "手", pronunciation: "shǒu", meaningVi: "tay", exampleSentence: "吃饭前要洗手。(Rửa tay trước khi ăn.)", topicTags: ["body"], level: "A1" },
    { word: "腿", pronunciation: "tuǐ", meaningVi: "chân", exampleSentence: "他上个月腿受伤了。(Tháng trước anh ấy bị thương chân.)", topicTags: ["body"], level: "A1" },
    { word: "眼睛", pronunciation: "yǎn jīng", meaningVi: "mắt", exampleSentence: "她的眼睛很漂亮。(Mắt cô ấy rất đẹp.)", topicTags: ["body"], level: "A1" },
    { word: "心", pronunciation: "xīn", meaningVi: "tim, trái tim", exampleSentence: "运动对心脏有好处。(Tập thể dục tốt cho tim.)", topicTags: ["body", "health"], level: "A1" },
    { word: "奶奶", pronunciation: "nǎi nai", meaningVi: "bà (nội)", exampleSentence: "我奶奶讲故事很好听。(Bà nội tôi kể chuyện rất hay.)", topicTags: ["family"], level: "A1" },
    { word: "爷爷", pronunciation: "yé ye", meaningVi: "ông (nội)", exampleSentence: "我爷爷八十岁了。(Ông nội tôi 80 tuổi rồi.)", topicTags: ["family"], level: "A1" },
    { word: "兄弟姐妹", pronunciation: "xiōng dì jiě mèi", meaningVi: "anh chị em ruột", exampleSentence: "我有两个兄弟姐妹。(Tôi có 2 anh chị em.)", topicTags: ["family"], level: "A2" },
    { word: "表哥", pronunciation: "biǎo gē", meaningVi: "anh họ", exampleSentence: "我表哥住在西贡。(Anh họ tôi sống ở Sài Gòn.)", topicTags: ["family"], level: "A2" },
    { word: "春天", pronunciation: "chūn tiān", meaningVi: "mùa xuân", exampleSentence: "春天花开了。(Mùa xuân hoa nở.)", topicTags: ["seasons"], level: "A1" },
    { word: "夏天", pronunciation: "xià tiān", meaningVi: "mùa hè", exampleSentence: "夏天我们去游泳。(Mùa hè chúng tôi đi bơi.)", topicTags: ["seasons"], level: "A1" },
    { word: "秋天", pronunciation: "qiū tiān", meaningVi: "mùa thu", exampleSentence: "秋天树叶落下来。(Mùa thu lá rụng.)", topicTags: ["seasons"], level: "A1" },
    { word: "冬天", pronunciation: "dōng tiān", meaningVi: "mùa đông", exampleSentence: "冬天下雪。(Mùa đông có tuyết.)", topicTags: ["seasons"], level: "A1" },
    { word: "一月", pronunciation: "yī yuè", meaningVi: "tháng Một", exampleSentence: "我的生日在一月。(Sinh nhật tôi vào tháng Một.)", topicTags: ["calendar"], level: "A1" },
    { word: "钱", pronunciation: "qián", meaningVi: "tiền", exampleSentence: "我没有很多钱。(Tôi không có nhiều tiền.)", topicTags: ["finance"], level: "A1" },
    { word: "银行", pronunciation: "yín háng", meaningVi: "ngân hàng", exampleSentence: "我需要去银行。(Tôi cần đi ngân hàng.)", topicTags: ["finance", "places"], level: "A1" },
    { word: "存钱", pronunciation: "cún qián", meaningVi: "tiết kiệm tiền", exampleSentence: "我每个月都存钱。(Mỗi tháng tôi đều tiết kiệm tiền.)", topicTags: ["finance", "verbs"], level: "A2" },
    { word: "工资", pronunciation: "gōng zī", meaningVi: "lương", exampleSentence: "她今年的工资涨了。(Lương của cô ấy năm nay tăng.)", topicTags: ["finance", "business"], level: "B1" },
    { word: "贵", pronunciation: "guì", meaningVi: "đắt", exampleSentence: "这家餐厅太贵了。(Nhà hàng này quá đắt.)", topicTags: ["finance", "adjectives"], level: "A1" },
    {
      word: "预算",
      pronunciation: "yù suàn",
      meaningVi: "ngân sách",
      exampleSentence: "我们要仔细计划预算。(Chúng ta cần lên kế hoạch ngân sách kỹ càng.)",
      topicTags: ["finance", "business"],
      level: "B1",
    },
    { word: "贷款", pronunciation: "dài kuǎn", meaningVi: "khoản vay", exampleSentence: "他们贷款买了房子。(Họ vay tiền để mua nhà.)", topicTags: ["finance"], level: "B1" },
    {
      word: "信用卡",
      pronunciation: "xìn yòng kǎ",
      meaningVi: "thẻ tín dụng",
      exampleSentence: "我用信用卡付款。(Tôi thanh toán bằng thẻ tín dụng.)",
      topicTags: ["finance", "shopping"],
      level: "A2",
    },
    { word: "现金", pronunciation: "xiàn jīn", meaningVi: "tiền mặt", exampleSentence: "你们收现金吗？(Bạn có nhận tiền mặt không?)", topicTags: ["finance", "shopping"], level: "A1" },
    {
      word: "收入",
      pronunciation: "shōu rù",
      meaningVi: "thu nhập",
      exampleSentence: "他的月收入很稳定。(Thu nhập hàng tháng của anh ấy rất ổn định.)",
      topicTags: ["finance", "business"],
      level: "B1",
    },
    { word: "善良", pronunciation: "shàn liáng", meaningVi: "tốt bụng", exampleSentence: "她对每个人都很善良。(Cô ấy tốt bụng với mọi người.)", topicTags: ["personality", "adjectives"], level: "A2" },
    { word: "幽默", pronunciation: "yōu mò", meaningVi: "hài hước", exampleSentence: "我哥哥很幽默。(Anh trai tôi rất hài hước.)", topicTags: ["personality", "adjectives"], level: "A2" },
    {
      word: "聪明",
      pronunciation: "cōng ming",
      meaningVi: "thông minh",
      exampleSentence: "她是班里最聪明的学生。(Cô ấy là học sinh thông minh nhất lớp.)",
      topicTags: ["personality", "adjectives"],
      level: "A1",
    },
    {
      word: "诚实",
      pronunciation: "chéng shí",
      meaningVi: "trung thực",
      exampleSentence: "他对我一直很诚实。(Anh ấy luôn trung thực với tôi.)",
      topicTags: ["personality", "adjectives"],
      level: "A2",
    },
    {
      word: "懒惰",
      pronunciation: "lǎn duò",
      meaningVi: "lười biếng",
      exampleSentence: "别懒惰，快写作业。(Đừng lười biếng, mau làm bài tập.)",
      topicTags: ["personality", "adjectives"],
      level: "A2",
    },
    { word: "起床", pronunciation: "qǐ chuáng", meaningVi: "thức dậy", exampleSentence: "我每天六点起床。(Tôi thức dậy lúc 6 giờ mỗi ngày.)", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "刷牙", pronunciation: "shuā yá", meaningVi: "đánh răng", exampleSentence: "我一天刷两次牙。(Tôi đánh răng 2 lần một ngày.)", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "洗澡", pronunciation: "xǐ zǎo", meaningVi: "tắm", exampleSentence: "我每天早上洗澡。(Tôi tắm mỗi sáng.)", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "穿衣服", pronunciation: "chuān yī fu", meaningVi: "mặc quần áo", exampleSentence: "她很快就穿好衣服了。(Cô ấy mặc quần áo rất nhanh.)", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "做饭", pronunciation: "zuò fàn", meaningVi: "nấu ăn", exampleSentence: "我爸爸每周五做饭。(Bố tôi nấu ăn mỗi thứ Sáu.)", topicTags: ["daily", "verbs", "food"], level: "A1" },
    { word: "谁", pronunciation: "shéi", meaningVi: "ai", exampleSentence: "那个人是谁？(Người đó là ai?)", topicTags: ["questions"], level: "A1" },
    { word: "什么", pronunciation: "shén me", meaningVi: "cái gì", exampleSentence: "你叫什么名字？(Tên bạn là gì?)", topicTags: ["questions"], level: "A1" },
    { word: "哪里", pronunciation: "nǎ lǐ", meaningVi: "ở đâu", exampleSentence: "你住在哪里？(Bạn sống ở đâu?)", topicTags: ["questions"], level: "A1" },
    { word: "什么时候", pronunciation: "shén me shí hou", meaningVi: "khi nào", exampleSentence: "你的生日是什么时候？(Sinh nhật bạn là khi nào?)", topicTags: ["questions"], level: "A1" },
    { word: "为什么", pronunciation: "wèi shén me", meaningVi: "tại sao", exampleSentence: "你为什么迟到？(Tại sao bạn đến muộn?)", topicTags: ["questions"], level: "A1" },
    { word: "怎么", pronunciation: "zěn me", meaningVi: "như thế nào", exampleSentence: "这个怎么用？(Cái này dùng như thế nào?)", topicTags: ["questions"], level: "A2" },
    { word: "四", pronunciation: "sì", meaningVi: "bốn", exampleSentence: "我有四本书。(Tôi có 4 quyển sách.)", topicTags: ["numbers"], level: "A1" },
    { word: "五", pronunciation: "wǔ", meaningVi: "năm", exampleSentence: "现在五点了。(Bây giờ là 5 giờ rồi.)", topicTags: ["numbers"], level: "A1" },
    { word: "六", pronunciation: "liù", meaningVi: "sáu", exampleSentence: "我六点起床。(Tôi thức dậy lúc 6 giờ.)", topicTags: ["numbers"], level: "A1" },
    { word: "七", pronunciation: "qī", meaningVi: "bảy", exampleSentence: "一周有七天。(Một tuần có 7 ngày.)", topicTags: ["numbers"], level: "A1" },
    { word: "八", pronunciation: "bā", meaningVi: "tám", exampleSentence: "我爷爷八十岁了。(Ông tôi 80 tuổi rồi.)", topicTags: ["numbers"], level: "A1" },
    { word: "九", pronunciation: "jiǔ", meaningVi: "chín", exampleSentence: "火车九点出发。(Tàu khởi hành lúc 9 giờ.)", topicTags: ["numbers"], level: "A1" },
    { word: "十", pronunciation: "shí", meaningVi: "mười", exampleSentence: "我有十个朋友。(Tôi có 10 người bạn.)", topicTags: ["numbers"], level: "A1" },
    { word: "快", pronunciation: "kuài", meaningVi: "nhanh", exampleSentence: "他跑得很快。(Anh ấy chạy rất nhanh.)", topicTags: ["adjectives"], level: "A1" },
    { word: "慢", pronunciation: "màn", meaningVi: "chậm", exampleSentence: "请说慢一点。(Xin hãy nói chậm hơn.)", topicTags: ["adjectives"], level: "A1" },
    { word: "山", pronunciation: "shān", meaningVi: "núi", exampleSentence: "我们上周末爬山了。(Cuối tuần trước chúng tôi leo núi.)", topicTags: ["nature"], level: "A1" },
    { word: "海", pronunciation: "hǎi", meaningVi: "biển", exampleSentence: "我喜欢在海里游泳。(Tôi thích bơi ở biển.)", topicTags: ["nature"], level: "A1" },
    { word: "森林", pronunciation: "sēn lín", meaningVi: "rừng", exampleSentence: "森林里有很多动物。(Trong rừng có nhiều động vật.)", topicTags: ["nature"], level: "A2" },
    { word: "天空", pronunciation: "tiān kōng", meaningVi: "bầu trời", exampleSentence: "今天天空很蓝。(Hôm nay bầu trời rất xanh.)", topicTags: ["nature"], level: "A1" },
    { word: "树", pronunciation: "shù", meaningVi: "cây", exampleSentence: "我家门前有一棵大树。(Trước nhà tôi có một cây to.)", topicTags: ["nature"], level: "A1" },
    { word: "刀", pronunciation: "dāo", meaningVi: "con dao", exampleSentence: "小心那把刀。(Cẩn thận con dao đó.)", topicTags: ["kitchen"], level: "A1" },
    { word: "勺子", pronunciation: "sháo zi", meaningVi: "cái thìa", exampleSentence: "请给我一个勺子。(Xin cho tôi một cái thìa.)", topicTags: ["kitchen"], level: "A1" },
    { word: "叉子", pronunciation: "chā zi", meaningVi: "cái nĩa", exampleSentence: "可以给我叉子吗？(Có thể cho tôi cái nĩa không?)", topicTags: ["kitchen"], level: "A1" },
    { word: "盘子", pronunciation: "pán zi", meaningVi: "cái đĩa", exampleSentence: "把食物放在盘子上。(Đặt thức ăn lên đĩa.)", topicTags: ["kitchen"], level: "A1" },
    { word: "锅", pronunciation: "guō", meaningVi: "cái nồi/chảo", exampleSentence: "妈妈用锅做饭。(Mẹ dùng nồi để nấu ăn.)", topicTags: ["kitchen"], level: "A2" },
    { word: "对不起", pronunciation: "duì bu qǐ", meaningVi: "xin lỗi", exampleSentence: "对不起，我迟到了。(Xin lỗi, tôi đến muộn.)", topicTags: ["social"], level: "A1" },
    { word: "不客气", pronunciation: "bú kè qi", meaningVi: "không có gì (đáp lại cảm ơn)", exampleSentence: "不客气！(Không có gì!)", topicTags: ["social"], level: "A1" },
    { word: "恭喜", pronunciation: "gōng xǐ", meaningVi: "chúc mừng", exampleSentence: "恭喜你！(Chúc mừng bạn!)", topicTags: ["social"], level: "A2" },
    { word: "没关系", pronunciation: "méi guān xi", meaningVi: "không sao đâu", exampleSentence: "没关系，别担心。(Không sao đâu, đừng lo.)", topicTags: ["social"], level: "A1" },
    { word: "欢迎", pronunciation: "huān yíng", meaningVi: "chào mừng, hoan nghênh", exampleSentence: "欢迎来到我家。(Chào mừng bạn đến nhà tôi.)", topicTags: ["social"], level: "A1" },
    { word: "强壮", pronunciation: "qiáng zhuàng", meaningVi: "khoẻ mạnh, mạnh mẽ", exampleSentence: "他很强壮。(Anh ấy rất khoẻ mạnh.)", topicTags: ["adjectives"], level: "A2" },
    { word: "弱", pronunciation: "ruò", meaningVi: "yếu", exampleSentence: "他身体很弱。(Sức khoẻ anh ấy yếu.)", topicTags: ["adjectives"], level: "A2" },
    { word: "容易", pronunciation: "róng yì", meaningVi: "dễ", exampleSentence: "这个练习很容易。(Bài tập này rất dễ.)", topicTags: ["adjectives"], level: "A1" },
    { word: "难", pronunciation: "nán", meaningVi: "khó", exampleSentence: "这个问题对我来说太难了。(Câu hỏi này quá khó với tôi.)", topicTags: ["adjectives"], level: "A1" },
    { word: "远", pronunciation: "yuǎn", meaningVi: "xa", exampleSentence: "学校离我家很远。(Trường học cách nhà tôi rất xa.)", topicTags: ["adjectives"], level: "A1" },
    { word: "近", pronunciation: "jìn", meaningVi: "gần", exampleSentence: "超市离这里很近。(Siêu thị ở gần đây.)", topicTags: ["adjectives"], level: "A1" },
    { word: "新", pronunciation: "xīn", meaningVi: "mới", exampleSentence: "我买了一件新衬衫。(Tôi đã mua một cái áo mới.)", topicTags: ["adjectives"], level: "A1" },
    { word: "旧", pronunciation: "jiù", meaningVi: "cũ", exampleSentence: "这是我的旧手机。(Đây là điện thoại cũ của tôi.)", topicTags: ["adjectives"], level: "A1" },
    { word: "干净", pronunciation: "gān jìng", meaningVi: "sạch sẽ", exampleSentence: "房间很干净。(Căn phòng rất sạch sẽ.)", topicTags: ["adjectives"], level: "A2" },
    { word: "脏", pronunciation: "zāng", meaningVi: "bẩn", exampleSentence: "你的鞋子很脏。(Giày của bạn rất bẩn.)", topicTags: ["adjectives"], level: "A2" },
  ];

  for (const word of chineseWords) {
    await prisma.vocabularyCard.upsert({
      where: { id: `zh-${word.word}` },
      update: {},
      create: {
        id: `zh-${word.word}`,
        languageId: zhLang.id,
        word: word.word,
        pronunciation: word.pronunciation,
        meaningVi: word.meaningVi,
        exampleSentence: word.exampleSentence,
        topicTags: word.topicTags,
        level: word.level as any,
      },
    });
  }

  // ─── Tiếng Nhật A1 (mẫu 10 từ) ───────────────────────────────────────────────
  const japaneseWords = [
    {
      word: "こんにちは",
      pronunciation: "konnichiwa",
      meaningVi: "xin chào (ban ngày)",
      exampleSentence: "こんにちは、元気ですか？(Xin chào, bạn khỏe không?)",
      topicTags: ["greetings"],
      level: "A1",
    },
    { word: "ありがとう", pronunciation: "arigatou", meaningVi: "cảm ơn", exampleSentence: "ありがとうございます。(Cảm ơn bạn rất nhiều.)", topicTags: ["greetings", "daily"], level: "A1" },
    { word: "さようなら", pronunciation: "sayounara", meaningVi: "tạm biệt", exampleSentence: "さようなら、またね！(Tạm biệt, hẹn gặp lại!)", topicTags: ["greetings"], level: "A1" },
    { word: "水", pronunciation: "mizu", meaningVi: "nước", exampleSentence: "水を飲みたい。(Tôi muốn uống nước.)", topicTags: ["food", "daily"], level: "A1" },
    { word: "食べる", pronunciation: "taberu", meaningVi: "ăn", exampleSentence: "ご飯を食べる。(Ăn cơm.)", topicTags: ["food", "verbs"], level: "A1" },
    { word: "友達", pronunciation: "tomodachi", meaningVi: "bạn bè", exampleSentence: "彼は私の友達です。(Anh ấy là bạn của tôi.)", topicTags: ["family", "daily"], level: "A1" },
    { word: "家", pronunciation: "ie / uchi", meaningVi: "nhà", exampleSentence: "家に帰ります。(Tôi về nhà.)", topicTags: ["home", "daily"], level: "A1" },
    { word: "仕事", pronunciation: "shigoto", meaningVi: "công việc", exampleSentence: "仕事が好きです。(Tôi thích công việc.)", topicTags: ["work"], level: "A1" },
    { word: "勉強", pronunciation: "benkyou", meaningVi: "học tập", exampleSentence: "日本語を勉強しています。(Tôi đang học tiếng Nhật.)", topicTags: ["education"], level: "A1" },
    { word: "好き", pronunciation: "suki", meaningVi: "thích", exampleSentence: "音楽が好きです。(Tôi thích âm nhạc.)", topicTags: ["daily", "adjectives"], level: "A1" },
    { word: "一", pronunciation: "ichi", meaningVi: "một", exampleSentence: "りんごが一つあります。(Có một quả táo.)", topicTags: ["numbers"], level: "A1" },
    { word: "二", pronunciation: "ni", meaningVi: "hai", exampleSentence: "友達が二人います。(Tôi có hai người bạn.)", topicTags: ["numbers"], level: "A1" },
    { word: "三", pronunciation: "san", meaningVi: "ba", exampleSentence: "今三時です。(Bây giờ là 3 giờ.)", topicTags: ["numbers"], level: "A1" },
    { word: "赤い", pronunciation: "akai", meaningVi: "màu đỏ", exampleSentence: "赤い花が好きです。(Tôi thích hoa màu đỏ.)", topicTags: ["colors", "adjectives"], level: "A1" },
    { word: "青い", pronunciation: "aoi", meaningVi: "màu xanh dương", exampleSentence: "空は青いです。(Bầu trời màu xanh.)", topicTags: ["colors", "adjectives"], level: "A1" },
    { word: "母", pronunciation: "haha", meaningVi: "mẹ (của mình)", exampleSentence: "母は先生です。(Mẹ tôi là giáo viên.)", topicTags: ["family"], level: "A1" },
    { word: "父", pronunciation: "chichi", meaningVi: "bố (của mình)", exampleSentence: "父はお茶が好きです。(Bố tôi thích trà.)", topicTags: ["family"], level: "A1" },
    { word: "今日", pronunciation: "kyou", meaningVi: "hôm nay", exampleSentence: "今日は天気がいいです。(Hôm nay thời tiết đẹp.)", topicTags: ["time"], level: "A1" },
    { word: "明日", pronunciation: "ashita", meaningVi: "ngày mai", exampleSentence: "明日学校に行きます。(Ngày mai tôi đi học.)", topicTags: ["time"], level: "A1" },
    { word: "時間", pronunciation: "jikan", meaningVi: "thời gian", exampleSentence: "時間がありません。(Tôi không có thời gian.)", topicTags: ["time"], level: "A2" },
    { word: "旅行", pronunciation: "ryokou", meaningVi: "du lịch", exampleSentence: "来月旅行します。(Tháng sau tôi đi du lịch.)", topicTags: ["travel"], level: "A2" },
    { word: "飛行機", pronunciation: "hikouki", meaningVi: "máy bay", exampleSentence: "飛行機で日本に行きます。(Tôi đi máy bay đến Nhật.)", topicTags: ["travel"], level: "A2" },
    { word: "病院", pronunciation: "byouin", meaningVi: "bệnh viện", exampleSentence: "彼は病院で働いています。(Anh ấy làm việc ở bệnh viện.)", topicTags: ["places"], level: "A2" },
    { word: "安い", pronunciation: "yasui", meaningVi: "rẻ", exampleSentence: "この携帯は安いです。(Cái điện thoại này rẻ.)", topicTags: ["shopping", "adjectives"], level: "A2" },
    { word: "経験", pronunciation: "keiken", meaningVi: "kinh nghiệm", exampleSentence: "彼は仕事の経験があります。(Anh ấy có kinh nghiệm làm việc.)", topicTags: ["work"], level: "B1" },
    { word: "機会", pronunciation: "kikai", meaningVi: "cơ hội", exampleSentence: "これはいい機会です。(Đây là một cơ hội tốt.)", topicTags: ["work"], level: "B1" },
    { word: "環境", pronunciation: "kankyou", meaningVi: "môi trường", exampleSentence: "環境を守らなければなりません。(Chúng ta phải bảo vệ môi trường.)", topicTags: ["nature"], level: "B1" },
    { word: "解決", pronunciation: "kaiketsu", meaningVi: "giải quyết", exampleSentence: "この問題を解決する必要があります。(Cần giải quyết vấn đề này.)", topicTags: ["verbs", "work"], level: "B1" },
    { word: "同僚", pronunciation: "douryou", meaningVi: "đồng nghiệp", exampleSentence: "同僚はとても親切です。(Đồng nghiệp của tôi rất tốt bụng.)", topicTags: ["work"], level: "B1" },
    {
      word: "自信",
      pronunciation: "jishin",
      meaningVi: "tự tin",
      exampleSentence: "面接の時、自信を持ってください。(Lúc phỏng vấn hãy tự tin nhé.)",
      topicTags: ["adjectives", "emotions"],
      level: "B1",
    },
    {
      word: "ストレス",
      pronunciation: "sutoresu",
      meaningVi: "căng thẳng, áp lực",
      exampleSentence: "仕事のストレスが多いです。(Áp lực công việc rất nhiều.)",
      topicTags: ["emotions", "work"],
      level: "B1",
    },
    { word: "成功", pronunciation: "seikou", meaningVi: "thành công", exampleSentence: "彼はついに成功しました。(Cuối cùng anh ấy đã thành công.)", topicTags: ["abstract"], level: "B1" },
    { word: "決める", pronunciation: "kimeru", meaningVi: "quyết định", exampleSentence: "まだ決めていません。(Tôi vẫn chưa quyết định.)", topicTags: ["verbs", "abstract"], level: "B1" },
    { word: "締め切り", pronunciation: "shimekiri", meaningVi: "hạn chót", exampleSentence: "締め切りは金曜日です。(Hạn chót là thứ Sáu.)", topicTags: ["work"], level: "B1" },
    { word: "晴れ", pronunciation: "hare", meaningVi: "trời nắng", exampleSentence: "今日は晴れです。(Hôm nay trời nắng.)", topicTags: ["weather"], level: "A1" },
    { word: "雨", pronunciation: "ame", meaningVi: "mưa", exampleSentence: "雨が降っています。(Trời đang mưa.)", topicTags: ["weather"], level: "A1" },
    { word: "寒い", pronunciation: "samui", meaningVi: "lạnh", exampleSentence: "冬は寒いです。(Mùa đông lạnh.)", topicTags: ["weather", "adjectives"], level: "A1" },
    { word: "暑い", pronunciation: "atsui", meaningVi: "nóng", exampleSentence: "夏は暑いです。(Mùa hè nóng.)", topicTags: ["weather", "adjectives"], level: "A1" },
    { word: "犬", pronunciation: "inu", meaningVi: "con chó", exampleSentence: "小さい犬がいます。(Tôi có một con chó nhỏ.)", topicTags: ["animals"], level: "A1" },
    { word: "猫", pronunciation: "neko", meaningVi: "con mèo", exampleSentence: "猫が寝ています。(Con mèo đang ngủ.)", topicTags: ["animals"], level: "A1" },
    { word: "鳥", pronunciation: "tori", meaningVi: "con chim", exampleSentence: "鳥は飛べます。(Chim biết bay.)", topicTags: ["animals"], level: "A1" },
    { word: "魚", pronunciation: "sakana", meaningVi: "con cá", exampleSentence: "夕食に魚を食べます。(Chúng tôi ăn cá cho bữa tối.)", topicTags: ["animals", "food"], level: "A1" },
    { word: "シャツ", pronunciation: "shatsu", meaningVi: "áo sơ mi", exampleSentence: "青いシャツを着ています。(Anh ấy mặc áo sơ mi màu xanh.)", topicTags: ["clothing"], level: "A1" },
    { word: "靴", pronunciation: "kutsu", meaningVi: "giày", exampleSentence: "この靴は履きやすいです。(Đôi giày này rất thoải mái.)", topicTags: ["clothing"], level: "A1" },
    { word: "サッカー", pronunciation: "sakkaa", meaningVi: "bóng đá", exampleSentence: "毎週末サッカーをします。(Anh ấy đá bóng mỗi cuối tuần.)", topicTags: ["sports"], level: "A1" },
    { word: "泳ぐ", pronunciation: "oyogu", meaningVi: "bơi lội", exampleSentence: "毎朝泳ぎます。(Tôi bơi mỗi sáng.)", topicTags: ["sports", "verbs"], level: "A1" },
    { word: "走る", pronunciation: "hashiru", meaningVi: "chạy", exampleSentence: "毎日五キロ走ります。(Cô ấy chạy bộ 5km mỗi ngày.)", topicTags: ["sports", "verbs"], level: "A1" },
    {
      word: "コンピューター",
      pronunciation: "konpyuutaa",
      meaningVi: "máy tính",
      exampleSentence: "仕事でコンピューターを使います。(Tôi dùng máy tính để làm việc.)",
      topicTags: ["technology"],
      level: "A1",
    },
    {
      word: "インターネット",
      pronunciation: "intaanetto",
      meaningVi: "internet, mạng",
      exampleSentence: "今日はインターネットが遅いです。(Hôm nay mạng rất chậm.)",
      topicTags: ["technology"],
      level: "A1",
    },
    {
      word: "携帯電話",
      pronunciation: "keitai denwa",
      meaningVi: "điện thoại di động",
      exampleSentence: "私の携帯電話は新しいです。(Điện thoại của tôi là mới.)",
      topicTags: ["technology"],
      level: "A1",
    },
    { word: "パスワード", pronunciation: "pasuwaado", meaningVi: "mật khẩu", exampleSentence: "パスワードを入力してください。(Vui lòng nhập mật khẩu.)", topicTags: ["technology"], level: "A2" },
    { word: "バス", pronunciation: "basu", meaningVi: "xe buýt", exampleSentence: "バスで学校に行きます。(Tôi đi xe buýt đến trường.)", topicTags: ["transport"], level: "A1" },
    { word: "電車", pronunciation: "densha", meaningVi: "tàu điện", exampleSentence: "電車は九時に出発します。(Tàu khởi hành lúc 9 giờ.)", topicTags: ["transport"], level: "A1" },
    { word: "自転車", pronunciation: "jitensha", meaningVi: "xe đạp", exampleSentence: "自転車で会社に行きます。(Cô ấy đi xe đạp đi làm.)", topicTags: ["transport"], level: "A1" },
    { word: "切符", pronunciation: "kippu", meaningVi: "vé", exampleSentence: "切符を二枚買いました。(Tôi đã mua hai vé.)", topicTags: ["travel"], level: "A2" },
    { word: "ホテル", pronunciation: "hoteru", meaningVi: "khách sạn", exampleSentence: "いいホテルに泊まりました。(Chúng tôi ở một khách sạn tốt.)", topicTags: ["travel", "places"], level: "A2" },
    {
      word: "パスポート",
      pronunciation: "pasupooto",
      meaningVi: "hộ chiếu",
      exampleSentence: "空港でパスポートを忘れないでください。(Đừng quên hộ chiếu ở sân bay.)",
      topicTags: ["travel"],
      level: "A2",
    },
    { word: "ご飯", pronunciation: "gohan", meaningVi: "cơm", exampleSentence: "毎日ご飯を食べます。(Chúng tôi ăn cơm mỗi ngày.)", topicTags: ["food"], level: "A1" },
    { word: "麺", pronunciation: "men", meaningVi: "mì", exampleSentence: "ベトナムの麺が好きです。(Tôi thích mì Việt Nam.)", topicTags: ["food"], level: "A1" },
    { word: "野菜", pronunciation: "yasai", meaningVi: "rau củ", exampleSentence: "野菜をもっと食べたほうがいいです。(Bạn nên ăn nhiều rau hơn.)", topicTags: ["food"], level: "A1" },
    { word: "コーヒー", pronunciation: "koohii", meaningVi: "cà phê", exampleSentence: "毎朝コーヒーを飲みます。(Tôi uống cà phê mỗi sáng.)", topicTags: ["food", "drinks"], level: "A1" },
    { word: "おいしい", pronunciation: "oishii", meaningVi: "ngon", exampleSentence: "この料理はおいしいです。(Món này rất ngon.)", topicTags: ["food", "adjectives"], level: "A1" },
    { word: "台所", pronunciation: "daidokoro", meaningVi: "nhà bếp", exampleSentence: "母は台所で料理をしています。(Mẹ đang nấu ăn trong bếp.)", topicTags: ["house"], level: "A1" },
    { word: "寝室", pronunciation: "shinshitsu", meaningVi: "phòng ngủ", exampleSentence: "私の寝室は二階にあります。(Phòng ngủ của tôi ở trên lầu.)", topicTags: ["house"], level: "A1" },
    { word: "庭", pronunciation: "niwa", meaningVi: "khu vườn", exampleSentence: "庭にたくさんの花があります。(Trong vườn có nhiều hoa.)", topicTags: ["house"], level: "A1" },
    { word: "医者", pronunciation: "isha", meaningVi: "bác sĩ", exampleSentence: "父は医者です。(Bố tôi là bác sĩ.)", topicTags: ["jobs"], level: "A1" },
    { word: "エンジニア", pronunciation: "enjinia", meaningVi: "kỹ sư", exampleSentence: "彼女はソフトウェアエンジニアです。(Cô ấy là kỹ sư phần mềm.)", topicTags: ["jobs"], level: "A2" },
    { word: "看護師", pronunciation: "kangoshi", meaningVi: "y tá", exampleSentence: "看護師が患者の世話をします。(Y tá chăm sóc bệnh nhân.)", topicTags: ["jobs"], level: "A1" },
    {
      word: "料理人",
      pronunciation: "ryourinin",
      meaningVi: "đầu bếp",
      exampleSentence: "彼はプロの料理人になりたいです。(Anh ấy muốn trở thành đầu bếp chuyên nghiệp.)",
      topicTags: ["jobs"],
      level: "A2",
    },
    { word: "弁護士", pronunciation: "bengoshi", meaningVi: "luật sư", exampleSentence: "彼女は弁護士を雇いました。(Cô ấy đã thuê một luật sư.)", topicTags: ["jobs"], level: "A2" },
    {
      word: "大学",
      pronunciation: "daigaku",
      meaningVi: "trường đại học",
      exampleSentence: "ハノイの大学で勉強しています。(Tôi học ở một trường đại học tại Hà Nội.)",
      topicTags: ["education"],
      level: "A2",
    },
    { word: "宿題", pronunciation: "shukudai", meaningVi: "bài tập về nhà", exampleSentence: "今夜宿題をしなければなりません。(Tối nay tôi phải làm bài tập.)", topicTags: ["education"], level: "A1" },
    { word: "試験", pronunciation: "shiken", meaningVi: "kỳ thi", exampleSentence: "試験は来週の月曜日です。(Kỳ thi là thứ Hai tuần sau.)", topicTags: ["education"], level: "A1" },
    { word: "卒業", pronunciation: "sotsugyou", meaningVi: "tốt nghiệp", exampleSentence: "彼女は去年卒業しました。(Cô ấy đã tốt nghiệp năm ngoái.)", topicTags: ["education", "verbs"], level: "B1" },
    { word: "頭痛", pronunciation: "zutsuu", meaningVi: "đau đầu", exampleSentence: "今日は頭痛がします。(Hôm nay tôi bị đau đầu.)", topicTags: ["health"], level: "A1" },
    { word: "熱", pronunciation: "netsu", meaningVi: "sốt", exampleSentence: "息子が熱を出しました。(Con trai tôi bị sốt.)", topicTags: ["health"], level: "A2" },
    { word: "薬", pronunciation: "kusuri", meaningVi: "thuốc", exampleSentence: "一日二回薬を飲んでください。(Uống thuốc 2 lần một ngày.)", topicTags: ["health"], level: "A2" },
    { word: "運動する", pronunciation: "undou suru", meaningVi: "tập thể dục", exampleSentence: "毎朝運動します。(Tôi tập thể dục mỗi sáng.)", topicTags: ["health", "verbs"], level: "A1" },
    {
      word: "健康",
      pronunciation: "kenkou",
      meaningVi: "khoẻ mạnh, sức khoẻ",
      exampleSentence: "野菜を食べるのは健康にいいです。(Ăn rau tốt cho sức khoẻ.)",
      topicTags: ["health", "adjectives"],
      level: "A1",
    },
    {
      word: "予約",
      pronunciation: "yoyaku",
      meaningVi: "cuộc hẹn, đặt trước",
      exampleSentence: "明日、病院の予約があります。(Ngày mai tôi có hẹn với bác sĩ.)",
      topicTags: ["health", "business"],
      level: "B1",
    },
    { word: "割引", pronunciation: "waribiki", meaningVi: "giảm giá", exampleSentence: "このシャツは割引があります。(Cái áo này được giảm giá.)", topicTags: ["shopping"], level: "A2" },
    { word: "レシート", pronunciation: "reshiito", meaningVi: "hoá đơn", exampleSentence: "レシートを保管してください。(Vui lòng giữ hoá đơn.)", topicTags: ["shopping"], level: "A2" },
    { word: "サイズ", pronunciation: "saizu", meaningVi: "kích cỡ", exampleSentence: "もっと大きいサイズはありますか？(Có kích cỡ lớn hơn không?)", topicTags: ["shopping"], level: "A1" },
    {
      word: "嬉しい",
      pronunciation: "ureshii",
      meaningVi: "hào hứng, vui mừng",
      exampleSentence: "旅行のことでとても嬉しいです。(Tôi rất hào hứng về chuyến đi này.)",
      topicTags: ["emotions", "adjectives"],
      level: "A1",
    },
    {
      word: "緊張する",
      pronunciation: "kinchou suru",
      meaningVi: "lo lắng, hồi hộp",
      exampleSentence: "試験の前に緊張しました。(Trước kỳ thi cô ấy rất hồi hộp.)",
      topicTags: ["emotions", "adjectives"],
      level: "A2",
    },
    {
      word: "がっかりする",
      pronunciation: "gakkari suru",
      meaningVi: "thất vọng",
      exampleSentence: "結果にがっかりしました。(Tôi rất thất vọng về kết quả.)",
      topicTags: ["emotions", "adjectives"],
      level: "B1",
    },
    {
      word: "つまらない",
      pronunciation: "tsumaranai",
      meaningVi: "chán",
      exampleSentence: "つまらないです。何か楽しいことをしましょう。(Tôi thấy chán, làm gì vui đi.)",
      topicTags: ["emotions", "adjectives"],
      level: "A1",
    },
    { word: "読書", pronunciation: "dokusho", meaningVi: "đọc sách (sở thích)", exampleSentence: "私の趣味は読書です。(Sở thích của tôi là đọc sách.)", topicTags: ["hobbies"], level: "A1" },
    { word: "絵を描く", pronunciation: "e o kaku", meaningVi: "vẽ tranh", exampleSentence: "彼女は暇な時に絵を描きます。(Cô ấy thích vẽ tranh lúc rảnh.)", topicTags: ["hobbies"], level: "A2" },
    { word: "写真撮影", pronunciation: "shashin satsuei", meaningVi: "nhiếp ảnh", exampleSentence: "写真撮影は彼の趣味です。(Nhiếp ảnh là đam mê của anh ấy.)", topicTags: ["hobbies"], level: "B1" },
    { word: "道", pronunciation: "michi", meaningVi: "đường phố, con đường", exampleSentence: "この道を左に曲がってください。(Rẽ trái ở đường này.)", topicTags: ["city", "directions"], level: "A1" },
    { word: "角", pronunciation: "kado", meaningVi: "góc, ngã tư", exampleSentence: "カフェは角にあります。(Quán cà phê ở góc đường.)", topicTags: ["city", "directions"], level: "A2" },
    { word: "まっすぐ", pronunciation: "massugu", meaningVi: "đi thẳng", exampleSentence: "二つ目の角までまっすぐ行ってください。(Đi thẳng qua 2 ngã tư.)", topicTags: ["directions"], level: "A2" },
    { word: "交通", pronunciation: "koutsuu", meaningVi: "giao thông", exampleSentence: "今朝は交通が混んでいます。(Sáng nay giao thông rất tắc.)", topicTags: ["city"], level: "A2" },
    {
      word: "混雑している",
      pronunciation: "konzatsu shiteiru",
      meaningVi: "đông đúc",
      exampleSentence: "週末の市場はとても混雑しています。(Cuối tuần chợ rất đông đúc.)",
      topicTags: ["city", "adjectives"],
      level: "B1",
    },
    { word: "世紀", pronunciation: "seiki", meaningVi: "thế kỷ", exampleSentence: "この建物は19世紀に建てられました。(Toà nhà này được xây vào thế kỷ 19.)", topicTags: ["time"], level: "B1" },
    { word: "最近", pronunciation: "saikin", meaningVi: "gần đây", exampleSentence: "最近彼に会っていません。(Gần đây tôi không gặp anh ấy.)", topicTags: ["time"], level: "B1" },
    {
      word: "ついに",
      pronunciation: "tsuini",
      meaningVi: "cuối cùng",
      exampleSentence: "ついに正しい道を見つけました。(Cuối cùng chúng tôi cũng tìm ra đường đúng.)",
      topicTags: ["time"],
      level: "B1",
    },
    { word: "すぐに", pronunciation: "sugu ni", meaningVi: "ngay lập tức", exampleSentence: "すぐに電話してください。(Hãy gọi cho tôi ngay lập tức.)", topicTags: ["time"], level: "B1" },
    {
      word: "延期する",
      pronunciation: "enki suru",
      meaningVi: "hoãn lại",
      exampleSentence: "会議を延期しなければなりませんでした。(Chúng tôi phải hoãn cuộc họp.)",
      topicTags: ["business", "verbs"],
      level: "B1",
    },
    {
      word: "参加する",
      pronunciation: "sanka suru",
      meaningVi: "tham dự",
      exampleSentence: "来週会議に参加します。(Tuần sau tôi sẽ tham dự hội nghị.)",
      topicTags: ["business", "verbs"],
      level: "B1",
    },
    {
      word: "招待する",
      pronunciation: "shoutai suru",
      meaningVi: "mời",
      exampleSentence: "彼女は誕生日パーティーに私を招待しました。(Cô ấy mời tôi dự tiệc sinh nhật.)",
      topicTags: ["verbs", "daily"],
      level: "A2",
    },
    { word: "頭", pronunciation: "atama", meaningVi: "đầu", exampleSentence: "頭が痛いです。(Đầu tôi rất đau.)", topicTags: ["body"], level: "A1" },
    { word: "手", pronunciation: "te", meaningVi: "tay", exampleSentence: "食べる前に手を洗ってください。(Rửa tay trước khi ăn.)", topicTags: ["body"], level: "A1" },
    { word: "足", pronunciation: "ashi", meaningVi: "chân", exampleSentence: "彼は先月足を怪我しました。(Tháng trước anh ấy bị thương chân.)", topicTags: ["body"], level: "A1" },
    { word: "目", pronunciation: "me", meaningVi: "mắt", exampleSentence: "彼女の目はきれいです。(Mắt cô ấy rất đẹp.)", topicTags: ["body"], level: "A1" },
    { word: "心臓", pronunciation: "shinzou", meaningVi: "tim", exampleSentence: "運動は心臓にいいです。(Tập thể dục tốt cho tim.)", topicTags: ["body", "health"], level: "A1" },
    { word: "祖母", pronunciation: "sobo", meaningVi: "bà", exampleSentence: "祖母は物語を話すのが上手です。(Bà tôi kể chuyện rất hay.)", topicTags: ["family"], level: "A1" },
    { word: "祖父", pronunciation: "sofu", meaningVi: "ông", exampleSentence: "祖父は80歳です。(Ông tôi 80 tuổi rồi.)", topicTags: ["family"], level: "A1" },
    { word: "兄弟姉妹", pronunciation: "kyoudai shimai", meaningVi: "anh chị em ruột", exampleSentence: "私は兄弟姉妹が二人います。(Tôi có 2 anh chị em.)", topicTags: ["family"], level: "A2" },
    { word: "いとこ", pronunciation: "itoko", meaningVi: "anh chị em họ", exampleSentence: "いとこはサイゴンに住んでいます。(Anh họ tôi sống ở Sài Gòn.)", topicTags: ["family"], level: "A2" },
    { word: "春", pronunciation: "haru", meaningVi: "mùa xuân", exampleSentence: "春に花が咲きます。(Mùa xuân hoa nở.)", topicTags: ["seasons"], level: "A1" },
    { word: "夏", pronunciation: "natsu", meaningVi: "mùa hè", exampleSentence: "夏に泳ぎに行きます。(Mùa hè chúng tôi đi bơi.)", topicTags: ["seasons"], level: "A1" },
    { word: "秋", pronunciation: "aki", meaningVi: "mùa thu", exampleSentence: "秋に葉が落ちます。(Mùa thu lá rụng.)", topicTags: ["seasons"], level: "A1" },
    { word: "冬", pronunciation: "fuyu", meaningVi: "mùa đông", exampleSentence: "冬に雪が降ります。(Mùa đông có tuyết.)", topicTags: ["seasons"], level: "A1" },
    { word: "一月", pronunciation: "ichigatsu", meaningVi: "tháng Một", exampleSentence: "私の誕生日は一月です。(Sinh nhật tôi vào tháng Một.)", topicTags: ["calendar"], level: "A1" },
    { word: "お金", pronunciation: "okane", meaningVi: "tiền", exampleSentence: "あまりお金がありません。(Tôi không có nhiều tiền.)", topicTags: ["finance"], level: "A1" },
    { word: "銀行", pronunciation: "ginkou", meaningVi: "ngân hàng", exampleSentence: "銀行に行く必要があります。(Tôi cần đi ngân hàng.)", topicTags: ["finance", "places"], level: "A1" },
    {
      word: "貯金する",
      pronunciation: "chokin suru",
      meaningVi: "tiết kiệm tiền",
      exampleSentence: "毎月貯金しています。(Mỗi tháng tôi đều tiết kiệm tiền.)",
      topicTags: ["finance", "verbs"],
      level: "A2",
    },
    { word: "給料", pronunciation: "kyuuryou", meaningVi: "lương", exampleSentence: "彼女の給料は今年上がりました。(Lương của cô ấy năm nay tăng.)", topicTags: ["finance", "business"], level: "B1" },
    { word: "高い", pronunciation: "takai", meaningVi: "đắt, cao", exampleSentence: "このレストランは高すぎます。(Nhà hàng này quá đắt.)", topicTags: ["finance", "adjectives"], level: "A1" },
    {
      word: "予算",
      pronunciation: "yosan",
      meaningVi: "ngân sách",
      exampleSentence: "予算を慎重に計画する必要があります。(Chúng ta cần lên kế hoạch ngân sách kỹ càng.)",
      topicTags: ["finance", "business"],
      level: "B1",
    },
    { word: "ローン", pronunciation: "roon", meaningVi: "khoản vay", exampleSentence: "彼らはローンで家を買いました。(Họ vay tiền để mua nhà.)", topicTags: ["finance"], level: "B1" },
    {
      word: "クレジットカード",
      pronunciation: "kurejitto kaado",
      meaningVi: "thẻ tín dụng",
      exampleSentence: "クレジットカードで払いました。(Tôi thanh toán bằng thẻ tín dụng.)",
      topicTags: ["finance", "shopping"],
      level: "A2",
    },
    { word: "現金", pronunciation: "genkin", meaningVi: "tiền mặt", exampleSentence: "現金は使えますか？(Bạn có nhận tiền mặt không?)", topicTags: ["finance", "shopping"], level: "A1" },
    {
      word: "収入",
      pronunciation: "shuunyuu",
      meaningVi: "thu nhập",
      exampleSentence: "彼の月収は安定しています。(Thu nhập hàng tháng của anh ấy rất ổn định.)",
      topicTags: ["finance", "business"],
      level: "B1",
    },
    {
      word: "優しい",
      pronunciation: "yasashii",
      meaningVi: "tốt bụng",
      exampleSentence: "彼女はみんなに優しいです。(Cô ấy tốt bụng với mọi người.)",
      topicTags: ["personality", "adjectives"],
      level: "A2",
    },
    {
      word: "面白い",
      pronunciation: "omoshiroi",
      meaningVi: "hài hước, thú vị",
      exampleSentence: "私の兄は面白いです。(Anh trai tôi rất hài hước.)",
      topicTags: ["personality", "adjectives"],
      level: "A1",
    },
    {
      word: "賢い",
      pronunciation: "kashikoi",
      meaningVi: "thông minh",
      exampleSentence: "彼女はクラスで一番賢いです。(Cô ấy là học sinh thông minh nhất lớp.)",
      topicTags: ["personality", "adjectives"],
      level: "A2",
    },
    {
      word: "正直",
      pronunciation: "shoujiki",
      meaningVi: "trung thực",
      exampleSentence: "彼はいつも私に正直です。(Anh ấy luôn trung thực với tôi.)",
      topicTags: ["personality", "adjectives"],
      level: "A2",
    },
    {
      word: "怠け者",
      pronunciation: "namakemono",
      meaningVi: "kẻ lười biếng",
      exampleSentence: "怠け者にならないでください。(Đừng lười biếng.)",
      topicTags: ["personality", "adjectives"],
      level: "B1",
    },
    { word: "起きる", pronunciation: "okiru", meaningVi: "thức dậy", exampleSentence: "毎日六時に起きます。(Tôi thức dậy lúc 6 giờ mỗi ngày.)", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "歯を磨く", pronunciation: "ha o migaku", meaningVi: "đánh răng", exampleSentence: "一日二回歯を磨きます。(Tôi đánh răng 2 lần một ngày.)", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "シャワーを浴びる", pronunciation: "shawaa o abiru", meaningVi: "tắm", exampleSentence: "毎朝シャワーを浴びます。(Tôi tắm mỗi sáng.)", topicTags: ["daily", "verbs"], level: "A1" },
    { word: "服を着る", pronunciation: "fuku o kiru", meaningVi: "mặc quần áo", exampleSentence: "彼女は早く服を着ます。(Cô ấy mặc quần áo rất nhanh.)", topicTags: ["daily", "verbs"], level: "A1" },
    {
      word: "料理する",
      pronunciation: "ryouri suru",
      meaningVi: "nấu ăn",
      exampleSentence: "父は毎週金曜日に料理します。(Bố tôi nấu ăn mỗi thứ Sáu.)",
      topicTags: ["daily", "verbs", "food"],
      level: "A1",
    },
    { word: "誰", pronunciation: "dare", meaningVi: "ai", exampleSentence: "あの人は誰ですか？(Người đó là ai?)", topicTags: ["questions"], level: "A1" },
    { word: "何", pronunciation: "nani", meaningVi: "cái gì", exampleSentence: "お名前は何ですか？(Tên bạn là gì?)", topicTags: ["questions"], level: "A1" },
    { word: "どこ", pronunciation: "doko", meaningVi: "ở đâu", exampleSentence: "どこに住んでいますか？(Bạn sống ở đâu?)", topicTags: ["questions"], level: "A1" },
    { word: "いつ", pronunciation: "itsu", meaningVi: "khi nào", exampleSentence: "誕生日はいつですか？(Sinh nhật bạn là khi nào?)", topicTags: ["questions"], level: "A1" },
    { word: "なぜ", pronunciation: "naze", meaningVi: "tại sao", exampleSentence: "なぜ遅れたのですか？(Tại sao bạn đến muộn?)", topicTags: ["questions"], level: "A1" },
    { word: "どう", pronunciation: "dou", meaningVi: "như thế nào", exampleSentence: "これはどう使いますか？(Cái này dùng như thế nào?)", topicTags: ["questions"], level: "A2" },
    { word: "四", pronunciation: "yon", meaningVi: "bốn", exampleSentence: "本を四冊持っています。(Tôi có 4 quyển sách.)", topicTags: ["numbers"], level: "A1" },
    { word: "五", pronunciation: "go", meaningVi: "năm", exampleSentence: "今五時です。(Bây giờ là 5 giờ rồi.)", topicTags: ["numbers"], level: "A1" },
    { word: "六", pronunciation: "roku", meaningVi: "sáu", exampleSentence: "六時に起きます。(Tôi thức dậy lúc 6 giờ.)", topicTags: ["numbers"], level: "A1" },
    { word: "七", pronunciation: "nana", meaningVi: "bảy", exampleSentence: "一週間は七日です。(Một tuần có 7 ngày.)", topicTags: ["numbers"], level: "A1" },
    { word: "八", pronunciation: "hachi", meaningVi: "tám", exampleSentence: "祖父は八十歳です。(Ông tôi 80 tuổi rồi.)", topicTags: ["numbers"], level: "A1" },
    { word: "九", pronunciation: "kyuu", meaningVi: "chín", exampleSentence: "電車は九時に出発します。(Tàu khởi hành lúc 9 giờ.)", topicTags: ["numbers"], level: "A1" },
    { word: "十", pronunciation: "juu", meaningVi: "mười", exampleSentence: "友達が十人います。(Tôi có 10 người bạn.)", topicTags: ["numbers"], level: "A1" },
    { word: "速い", pronunciation: "hayai", meaningVi: "nhanh", exampleSentence: "彼は走るのが速いです。(Anh ấy chạy rất nhanh.)", topicTags: ["adjectives"], level: "A1" },
    { word: "遅い", pronunciation: "osoi", meaningVi: "chậm", exampleSentence: "もっとゆっくり話してください。(Xin hãy nói chậm hơn.)", topicTags: ["adjectives"], level: "A1" },
    { word: "山", pronunciation: "yama", meaningVi: "núi", exampleSentence: "先週末、山に登りました。(Cuối tuần trước chúng tôi leo núi.)", topicTags: ["nature"], level: "A1" },
    { word: "海", pronunciation: "umi", meaningVi: "biển", exampleSentence: "海で泳ぐのが好きです。(Tôi thích bơi ở biển.)", topicTags: ["nature"], level: "A1" },
    { word: "森", pronunciation: "mori", meaningVi: "rừng", exampleSentence: "森にはたくさんの動物がいます。(Trong rừng có nhiều động vật.)", topicTags: ["nature"], level: "A2" },
    { word: "空", pronunciation: "sora", meaningVi: "bầu trời", exampleSentence: "今日は空が青いです。(Hôm nay bầu trời rất xanh.)", topicTags: ["nature"], level: "A1" },
    { word: "木", pronunciation: "ki", meaningVi: "cây", exampleSentence: "家の前に大きい木があります。(Trước nhà tôi có một cây to.)", topicTags: ["nature"], level: "A1" },
    { word: "ナイフ", pronunciation: "naifu", meaningVi: "con dao", exampleSentence: "そのナイフに気をつけてください。(Cẩn thận con dao đó.)", topicTags: ["kitchen"], level: "A1" },
    { word: "スプーン", pronunciation: "supuun", meaningVi: "cái thìa", exampleSentence: "スプーンをください。(Xin cho tôi một cái thìa.)", topicTags: ["kitchen"], level: "A1" },
    { word: "フォーク", pronunciation: "fooku", meaningVi: "cái nĩa", exampleSentence: "フォークをもらえますか？(Có thể cho tôi cái nĩa không?)", topicTags: ["kitchen"], level: "A1" },
    { word: "お皿", pronunciation: "osara", meaningVi: "cái đĩa", exampleSentence: "食べ物をお皿に置いてください。(Đặt thức ăn lên đĩa.)", topicTags: ["kitchen"], level: "A1" },
    { word: "鍋", pronunciation: "nabe", meaningVi: "cái nồi", exampleSentence: "母は鍋で料理します。(Mẹ dùng nồi để nấu ăn.)", topicTags: ["kitchen"], level: "A2" },
    { word: "すみません", pronunciation: "sumimasen", meaningVi: "xin lỗi, xin phép", exampleSentence: "すみません、遅れました。(Xin lỗi, tôi đến muộn.)", topicTags: ["social"], level: "A1" },
    {
      word: "どういたしまして",
      pronunciation: "dou itashimashite",
      meaningVi: "không có gì (đáp lại cảm ơn)",
      exampleSentence: "どういたしまして！(Không có gì!)",
      topicTags: ["social"],
      level: "A1",
    },
    { word: "おめでとう", pronunciation: "omedetou", meaningVi: "chúc mừng", exampleSentence: "おめでとうございます！(Xin chúc mừng!)", topicTags: ["social"], level: "A2" },
    { word: "大丈夫", pronunciation: "daijoubu", meaningVi: "không sao đâu, ổn", exampleSentence: "大丈夫、心配しないで。(Không sao đâu, đừng lo.)", topicTags: ["social"], level: "A1" },
    { word: "ようこそ", pronunciation: "youkoso", meaningVi: "chào mừng", exampleSentence: "私の家へようこそ。(Chào mừng bạn đến nhà tôi.)", topicTags: ["social"], level: "A1" },
    { word: "強い", pronunciation: "tsuyoi", meaningVi: "mạnh mẽ, khoẻ", exampleSentence: "彼はとても強いです。(Anh ấy rất khoẻ mạnh.)", topicTags: ["adjectives"], level: "A2" },
    { word: "弱い", pronunciation: "yowai", meaningVi: "yếu", exampleSentence: "彼は体が弱いです。(Sức khoẻ anh ấy yếu.)", topicTags: ["adjectives"], level: "A2" },
    { word: "簡単", pronunciation: "kantan", meaningVi: "dễ, đơn giản", exampleSentence: "この練習はとても簡単です。(Bài tập này rất dễ.)", topicTags: ["adjectives"], level: "A1" },
    { word: "難しい", pronunciation: "muzukashii", meaningVi: "khó", exampleSentence: "この質問は難しすぎます。(Câu hỏi này quá khó với tôi.)", topicTags: ["adjectives"], level: "A1" },
    { word: "遠い", pronunciation: "tooi", meaningVi: "xa", exampleSentence: "学校は家から遠いです。(Trường học cách nhà tôi rất xa.)", topicTags: ["adjectives"], level: "A1" },
    { word: "近い", pronunciation: "chikai", meaningVi: "gần", exampleSentence: "スーパーはここから近いです。(Siêu thị ở gần đây.)", topicTags: ["adjectives"], level: "A1" },
    { word: "新しい", pronunciation: "atarashii", meaningVi: "mới", exampleSentence: "新しいシャツを買いました。(Tôi đã mua một cái áo mới.)", topicTags: ["adjectives"], level: "A1" },
    { word: "古い", pronunciation: "furui", meaningVi: "cũ", exampleSentence: "これは私の古い携帯電話です。(Đây là điện thoại cũ của tôi.)", topicTags: ["adjectives"], level: "A1" },
    { word: "きれい", pronunciation: "kirei", meaningVi: "sạch sẽ, đẹp", exampleSentence: "部屋がきれいです。(Căn phòng rất sạch sẽ.)", topicTags: ["adjectives"], level: "A2" },
    { word: "汚い", pronunciation: "kitanai", meaningVi: "bẩn", exampleSentence: "靴がとても汚いです。(Giày của bạn rất bẩn.)", topicTags: ["adjectives"], level: "A2" },
  ];

  for (const word of japaneseWords) {
    await prisma.vocabularyCard.upsert({
      where: { id: `ja-${word.word}` },
      update: {},
      create: {
        id: `ja-${word.word}`,
        languageId: jaLang.id,
        word: word.word,
        pronunciation: word.pronunciation,
        meaningVi: word.meaningVi,
        exampleSentence: word.exampleSentence,
        topicTags: word.topicTags,
        level: word.level as any,
      },
    });
  }

  console.log(`  ✓ Vocabulary seeded: ${englishWords.length} EN, ${chineseWords.length} ZH, ${japaneseWords.length} JA`);
}
